### PR TITLE
+ add plugin to execute JMeter scenario

### PR DESCRIPTION
**Pull request by sebastien-prudhomme**
Inspired by the Selenium plugin, a new plugin to execute JMeter scenarios locally or by SSH.
Use the JMeter log file in XML format: http://jmeter.apache.org/usermanual/listeners.html

### CODE REVIEW

**Comment by garnier-quentin** [comment]
The code seems good. But does jmeter have an api ? I don't really like to launch a java process if we can avoid it :)

**Comment by karhm** [comment]
Excellent !! it's been a while since i search a Centreon plugin for Jmeter, after few test it's seem working perfectly, far better than the old jmeter plugin i use

**Comment by sebastien-prudhomme** [comment]
@garnier-quentin: no modern web API at all

Either you launch it in standalone mode, as i do, or you have "slave" servers but the communication with them still need to launch a JMeter java process to communicate with the servers (with RMI communication in both sides...)

**Comment by garnier-quentin** [comment]
I have seen that but maybe i have not looked well. That's a shame. I will look the PR in details

**Comment by karhm** [comment]
@sebastien-prudhomme 
i tried to use the plugin in remote mode but i have this error:
```
UNKNOWN:
no element found at line 1, column 0, byte 0 at /usr/lib64/perl5/vendor_perl/XML/Parser.pm line 187.
```
here is my command:
`/usr/lib/centreon/plugins/centreon_plugins.pl --plugin=apps::jmeter::plugin --mode=scenario --remote --hostname=10.179.3.55 --ssh-option='-l=centreon-engine' --command-path=/usr/lib/jmeter/bin/ --directory=/usr/lib/jmeter/plan/ --scenario=B66_FOV_01 --warning= --critical= --timeout=60 --verbose`

i try to execute the plugin from my centreon central server, jmeter is installed on 10.179.3.55 server which is also a centreon poller.
when i launch the plugin localy from 10.179.3.55 no problem:
```
/usr/lib/centreon/plugins/centreon_plugins.pl --plugin=apps::jmeter::plugin --mode=scenario --command-path=/usr/lib/jmeter/bin/ --directory=/usr/lib/jmeter/plan/ --scenario=B66_FOV_01 --warning= --critical= --timeout=60 --verbose

OK: 2/2 steps (0.121s) | 'time'=0.121s;;;0; 'steps'=2;;;0;2 'availability'=100%;;;0;100
```
do you have any hint, where's my mistake ?

**Comment by sebastien-prudhomme** [comment]
@karhm no mistake, remote mode is a wrong copy/paste that just can't work...because the XML result is in a temporary local file and the file is not copied back to the first server.

**Comment by sebastien-prudhomme** [comment]
@karhm it should work with remote mode with the last commit

**Comment by karhm** [comment]
@sebastien-prudhomme Thx, i'll try to test this today. Again thx for this great work !

**Comment by garnier-quentin** [comment]
I'm waiting for the feedback of @karhm

**Comment by karhm** [comment]
@garnier-quentin 
the remote mode works perfectly now
I play around 50 Jmeter Plan attached to 4 different poller and Jmeter is on a dedicated server that supports all ressource load, it's just perfect.

**Pull request merged**
