### PR TITLE
Check Oracle ASM diskgroup usage and statut

### PR DESCRIPTION
**Pull request by Gilum**
[root@###]# ./centreon_plugins.pl --plugin=database::oracle::plugin --mode=asm-diskgroup-usage --warning=90 --critical=95 --connect-options='ora_session_mode=32768' --hostname=##### --datasource="Oracle://#####:1521/+ASM" --username=### --password=###
OK: All diskgroup are ok. | 'dg_data_fc_usage'=606982897664B;0:628138967040;0:663035576320;0;697932185600 'dg_fra_sata_usage'=15384707072B;0:96636764160;0:102005473280;0;107374182400

### CODE REVIEW

**Comment by garnier-quentin** [comment]
Thanks. I have done some changes. Could you test please ?

**Comment by Gilum** [comment]
perfdata and used not working :( snif

**Comment by garnier-quentin** [comment]
Could you give me the ouput  please ?

**Comment by Gilum** [comment]
With my script :
 ./centreon_plugins.pl --plugin=database::oracle::plugin --mode=asm-diskgroup-usage --warning=90 --critical=95 --connect-options='ora_session_mode=32768' --hostname=### --datasource="Oracle://###:1521/+ASM" --username=### --password=###
WARNING: dg 'DATA_FC' Used: ###.43TB (92.04%) Size: ###.64TB | 'dg_crs_fc_usage'=###B;0:###;0:###;0;### 'dg_data_fc_usage'=###B;0:###;0:###;0;### 'dg_fra_fc_usage'=###B;0:###;0:###;0;###


With your script :
./centreon_plugins.pl --plugin=database::oracle::plugin --mode=asm-diskgroup-usage --warning-usage=90 --critical-usage=95 --connect-options='ora_session_mode=32768' --hostname=### --datasource="Oracle://###:1521/+ASM" --username=### --password=###
OK: All diskgroups are ok |

**Comment by garnier-quentin** [comment]
Could you do it with the option --verbose --debug also ?

Thanks.

**Comment by Gilum** [comment]
OK: All diskgroups are ok |
Diskgroup 'CRS_FC' Status : MOUNTED, Offline disks : 0
Diskgroup 'DATA_FC' Status : MOUNTED, Offline disks : 0
Diskgroup 'FRA_FC' Status : MOUNTED, Offline disks : 0

**Comment by garnier-quentin** [comment]
Could you test it now with the last version ? I have fixed it i think.

**Comment by Gilum** [comment]
fix usage #142

**Pull request merged**
