### PR TITLE
add proxmox ve plugin

### PR DESCRIPTION
**Pull request by cgagnaire**
Based on @ypilpre branch from PR https://github.com/centreon/centreon-plugins/pull/1267 but without last commit.

### CODE REVIEW

**Comment by ypilpre** [comment]
I can't guarantee that Proxmox 4 is compatible with this plugin. A lot of changes occured with Proxmox 5.x Release.

**Comment by cgagnaire** [comment]
We'll see :)

**Comment by cgagnaire** [comment]
Closes https://github.com/centreon/centreon-plugins/pull/1267

**Comment by cgagnaire** [comment]
Just tested with v5.2, works like a charm.
Thanks again @ypilpre !

**Comment by freddL** [comment]
Hi,
my server is CentOS 6.10
centreon version : 2.8.26
perl -E'say $^X' --> /usr/bin/perl
cpan JSON
CPAN: Storable loaded ok (v2.20)
Going to read '/root/.cpan/Metadata'
  Database was generated on Wed, 12 Dec 2018 12:17:03 GMT
JSON is up to date (4.00).
error : 
UNKNOWN: Cannot load module --custommode. 
Can't locate JSON/XS.pm in @INC (@INC contains: /usr/lib/nagios/plugins/centreon-plugins /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /usr/lib/nagios/plugins/centreon-plugins/apps/proxmox/ve/restapi/custom/api.pm line 29.
thanks

**Comment by freddL** [comment]
thank you ypipre !
but I have a new error : UNKNOWN: Cannot decode json response

**Comment by ypilpre** [comment]
Could you send me your Proxmox Config ? Is it a 5.x version ?

**Comment by freddL** [comment]
proxmox 5.3-5
pvesh
ERROR: no command specified
USAGE: pvesh <COMMAND> [ARGS] [OPTIONS]

**Comment by ypilpre** [comment]
Ok, I made all dev on 5.2.1 version (5.3 was release only last week !)

I will upgrade my dev plateform in order to test more depthly the plugins.

Could you please send me the check (or discovery) commands you send  like this : 

`/usr/lib/centreon/plugins/centreon_proxmox_ve_restapi.pl --plugin=apps::proxmox::ve::restapi::plugin --mode=node-usage --hostname='IPOFTHEPROXMOXNODE' --api_username= PROXMOXUSER --api_password= PROXMOXPASSWORD --port='8006'  --node-id='' --node-name='' --filter-name='' --warning-node-status='' --critical-node-status='' --warning-cpu='' --critical-cpu='' --warning-memory='' --critical-memory='' --warning-swap='' --critical-swap='' --warning-fs='' --critical-fs='' --ssl-opt="SSL_verify_mode => SSL_VERIFY_NONE"   `

Replace IPOFTHEPROXMOXNODE, PROXMOXUSER and  PROXMOXPASSWORD with your own ip and credentials

**Comment by ypilpre** [comment]
So I upgrade my Proxmox to 5.3, and I have no error about decode json running this command.

But my dev version is not a cluster, juste one node. (My Prod cluster is a 5.2, and no upgrade are plan right now).

I noticied that pvesh command change (no more "pve" shell, juste command like openstack).
but the PVE API documentation have no specific change with 5.3...

**Comment by ypilpre** [comment]
Also could you please test a api request directly with Postman (following this doc about Auth cookie)

`https://IPROXMOX:8006/api2/json/cluster/resources?type=node`

and post the result ?

**Comment by freddL** [comment]
data |  
-- | --
0 |  
disk | 14363009024
level | ""
id | "node/pve-02"
maxmem | 33629917184
type | "node"
maxdisk | 35535929344
cpu | 0.0160892381945856
uptime | 5362234
maxcpu | 24
node | "pve-02"
status | "online"
mem | 26198843392
1 |  
type | "node"
maxdisk | 35535929344
maxcpu | 24
node | "pve-03"
uptime | 5093723
cpu | 0.0205460443141476
mem | 16402395136
status | "online"
disk | 12600926208
level | ""
id | "node/pve-03"
maxmem | 33629925376
2 |  
maxmem | 33632182272
id | "node/pve-01"
level | ""
disk | 13801648128
status | "online"
mem | 17958199296
cpu | 0.138974682441052
uptime | 5091764
maxcpu | 12
node | "pve-01"
maxdisk | 35800154112
type | "node"

**Comment by ypilpre** [comment]
It's not a json file ??

**Comment by freddL** [comment]
json format :
{"data":[{"disk":14363009024,"level":"","id":"node/pve-02","maxmem":33629917184,"type":"node","maxdisk":35535929344,"cpu":0.0160892381945856,"uptime":5362234,"maxcpu":24,"node":"pve-02","status":"online","mem":26198843392},{"type":"node","maxdisk":35535929344,"maxcpu":24,"node":"pve-03","uptime":5093723,"cpu":0.0205460443141476,"mem":16402395136,"status":"online","disk":12600926208,"level":"","id":"node/pve-03","maxmem":33629925376},{"maxmem":33632182272,"id":"node/pve-01","level":"","disk":13801648128,"status":"online","mem":17958199296,"cpu":0.138974682441052,"uptime":5091764,"maxcpu":12,"node":"pve-01","maxdisk":35800154112,"type":"node"}]}

**Comment by ypilpre** [comment]
May be you use the #1269 

You need to use the #1270 release
The JSON::XS has been removed in this version.

**Comment by ypilpre** [comment]
Ok, could you please test this branch from my Git

[https://github.com/ypilpre/centreon-plugins/tree/proxmox-ve](https://github.com/ypilpre/centreon-plugins/tree/proxmox-ve)

I remove the JSON::XS and it use only JSON Module for decoding.

**Comment by freddL** [comment]
I tried your repo, I have a new problem :
Unknown option: api-username at centreon-plugins-proxmox-ve/centreon/plugins/alternative/Getopt.pm line 67
From original plugin, In file apps/proxmox/ve/restapi/custom/api.pm I changed  JSON::XS by JSON but I have always this problem : UNKNOWN: Cannot decode json response
I think this my problem is from my server centreon

**Comment by ypilpre** [comment]
I will rebase my code on centreon branch in order to clean my mess...

**Comment by ypilpre** [comment]
Ok, from my side, I've no problem (just the api-username/api_username change)
and I use the JSON::XS

**Pull request merged**
