### PR TITLE
Add default option for ElasticSearch Plugin

### PR DESCRIPTION
**Pull request by fixlair**

### CODE REVIEW

**Comment by garnier-quentin** [comment]
Thanks. But it's not needed. It's by default in the http lib.

**Comment by fixlair** [comment]
Hello,
Thanks for you reactivity Quentin. But when I test on the updated master i've got the following : 

./centreon_plugins.pl --plugin=apps::elasticsearch::plugin --mode=cluster --hostname=XXX.XXX.XXX.XXX
Use of uninitialized value in concatenation (.) or string at /var/lib/centreon/plugins/apps/elasticsearch/mode/cluster.pm line 80.


./centreon_plugins.pl --plugin=apps::elasticsearch::plugin --mode=cluster --hostname=XXX.XXX.XXX.XXX --port=9200 --urlpath=/
WARNING: Primary shards are allocated but replicas not for es_rpc_preprod | 'primary_shard'=5;;;0; 'shard'=5;;;0; 'unassigned_shard'=5;;;0;

**Comment by garnier-quentin** [comment]
You use the last github version ?

**Comment by garnier-quentin** [comment]
Done. Could you test it ?

**Comment by fixlair** [comment]
It works great !
Thank you !!!
(I just get the way you did the change :))

**Pull request closed without merging**
