### PR TITLE
new plugin for SmarterMail API

### PR DESCRIPTION
**Pull request by rmorandell-pgum**
**Plugin to get information from SmarterMail API**

https://mail.smartertools.com/Documentation/api#/topics/overview

Authentication via username and password to get the JWT. Writes the JWT in a cache file in order to reuse it for later queries up to its expiration date

### **** Modes: services, spoolmessagecount, licensenotifications

**mode=services**

https://mail.smartertools.com/Documentation/api#/reference/SmarterMail.Web.Controllers.Api.SystemAdminSettingsController/GetServices

checks if services are in running state

services: 'spool', 'smtp', 'pop', 'xmpp', 'imap', 'ldap', 'popretrieval', 'imapretrieval', 'indexing'

perl /usr/lib/centreon/plugins/centreon_plugins.pl --plugin=apps::smartermail::restapi::plugin --mode=services --hostname='webmail.example.com' --username=username --password='***password***' 

**filter option**

perl /usr/lib/centreon/plugins/centreon_plugins.pl --plugin=apps::smartermail::restapi::plugin --mode=services --hostname='webmail.example.com' --username=username --password='***password***' --filter-service='spool|smtp|pop|imap'

**critical-status**

perl /usr/lib/centreon/plugins/centreon_plugins.pl --plugin=apps::smartermail::restapi::plugin --mode=services --hostname='webmail.example.com' --username=username --password='***password***' --filter-service='spool|smtp|pop|imap' --critical-status='%{state_absolute} !~ /running/'

*********************

**mode=spoolmessagecount**

https://mail.smartertools.com/Documentation/api#/reference/SmarterMail.Web.Controllers.Api.SystemAdminSettingsController/GetSpoolMessageCounts

perl /usr/lib/centreon/plugins/centreon_plugins.pl --plugin=apps::smartermail::restapi::plugin --mode=spoolmessagecount --hostname=webmail.example.com --username=username --password='***password***' --warning-default= --warning-waiting= --warning-spam= --warning-virus= --critical-default= --critical-waiting= --critical-spam= --critical-virus=

**filter option**

perl /usr/lib/centreon/plugins/centreon_plugins.pl --plugin=apps::smartermail::restapi::plugin --mode=spoolmessagecount --hostname=webmail.example.com --username=username --password='***password***' --warning-default= --warning-waiting= --warning-spam= --warning-virus= --critical-default= --critical-waiting= --critical-spam= --critical-virus= --filter-counter='waiting|spam|virus'

*********************

**mode=licensenotifications**

gets information about the license state. 

https://mail.smartertools.com/Documentation/api#/reference/SmarterMail.Web.Controllers.Api.SystemAdminSettingsController/GetLicenseNotifications

perl /usr/lib/centreon/plugins/centreon_plugins.pl --plugin=apps::smartermail::restapi::plugin --mode=licensenotifications --hostname='webmail.example.com' --username=username --password='***password***' --warning-daysUntilUpgradeProtectionExpires=50: --critical-daysUntilUpgradeProtectionExpires=30:

### CODE REVIEW

**Comment by garnier-quentin** [comment]
Could you provide curl results for each type API calls ?

**Comment by rmorandell-pgum** [comment]
curl --location --request POST 'https://webmail.example.com/api/v1/auth/authenticate-user' --header 'Content-Type: application/json' --data '{ "username": "example_user", "password": "***password" }'
 
curl --location --request GET 'https://webmail.example.com/api/v1/settings/sysadmin/spool-message-counts' --header 'Content-Type: application/json' -H 'Authorization: Bearer <<TOKEN>>'
 
curl --location --request GET 'https://webmail.example.com/api/v1/settings/sysadmin/license-notifications' --header 'Content-Type: application/json' -H 'Authorization: Bearer <<TOKEN>>'

curl --location --request GET 'https://webmail.example.com/api/v1/settings/sysadmin/services' --header 'Content-Type: application/json' -H 'Authorization: Bearer <<TOKEN>>'

**Comment by rmorandell-pgum** [comment]
For your information: I made a commit because I still had to make a change for mode services. Today we updated to the new plugin version 2020-10-08 and I had to change the counter for "state" from "state_absolute" to simply "state". The plugin works without any problems

image

**Comment by garnier-quentin** [comment]
I have done some changes. Could you test it ?

**Comment by rmorandell-pgum** [comment]
Hi,

it's not working

for all 3 modes the same error. 

*************

perl /tmp/centreon-plugins-master/centreon_plugins.pl --plugin=apps::smartermail::restapi::plugin --mode=services --hostname='webmail.***' --api-username=*** --api-password='***'
Use of uninitialized value in concatenation (.) or string at /tmp/centreon-plugins-master/apps/smartermail/restapi/custom/api.pm line 206.
Use of uninitialized value in concatenation (.) or string at /tmp/centreon-plugins-master/apps/smartermail/restapi/custom/api.pm line 206.
UNKNOWN: Cannot decode json response: malformed JSON string, neither tag, array, object, number, string or atom, at character offset 0 (before "content") at /tmp/centreon-plugins-master/apps/smartermail/restapi/custom/api.pm line 124.

***************

in my version of the plugin i decoded the json with JSON::XS

my $jsonResponse = $options{custom}->get_endpoint(api_path => '/settings/sysadmin/services');
   
    my $response;
    eval {
        $response = decode_json($jsonResponse);
    };

**Comment by garnier-quentin** [comment]
Could you test with last version please ?

**Comment by rmorandell-pgum** [comment]
Still the same error ..

Downloaded the latest fix of today .. on the right side of the sceen the file on the system 

image

**Comment by rmorandell-pgum** [comment]
just for completion the response of authentication via curl

 curl --location --request POST 'https://webmail.***/api/v1/auth/authenticate-user' --header 'Content-Type: application/json' --data '{ "username": "***", "password": "***" }'
{"emailAddress":"","changePasswordNeeded":false,"displayWelcomeWizard":false,"isAdmin":true,"isDomainAdmin":false,"isLicensed":true,"autoLoginToken":"","autoLoginUrl":"","isImpersonating":false,"canViewPasswords":false,"accessToken":"***","refreshToken":"***","accessTokenExpiration":"2020-10-28T14:18:21.5589952Z","username":"sidera_ivertix@","success":true,"resultCode":200}

**Comment by garnier-quentin** [comment]
Could you provide the result with --debug option ?

**Comment by rmorandell-pgum** [comment]
the debug shows that the authentication was successfull and the token was returned. On the request to get the spool datathe token its missing in the authentication header

======> request send
POST https://webmail***:443/api/v1/auth/authenticate-user
Accept: application/json
User-Agent: centreon::plugins::backend::http::useragent
Content-Type: application/json

{"password":"-","username":"_"}

======> response done
HTTP/1.1 200 OK
Cache-Control: no-cache
Date: Wed, 28 Oct 2020 14:12:54 GMT
Pragma: no-cache
Server: Microsoft-IIS/10.0
Content-Length: 2206
Content-Type: application/json; charset=utf-8
Expires: -1
Access-Control-Allow-Origin: *
Client-Date: Wed, 28 Oct 2020 14:12:54 GMT
Client-Peer: 46.234.233.53:443
Client-Response-Num: 1
Client-SSL-Cert-Issuer: /C=GB/ST=Greater Manchester/L=Salford/O=Sectigo Limited/CN=Sectigo RSA Domain Validation Secure Server CA
Client-SSL-Cert-Subject: /CN=***removed***
Client-SSL-Cipher: ECDHE-RSA-AES256-GCM-SHA384
Client-SSL-Socket-Class: IO::Socket::SSL

{"emailAddress":"","changePasswordNeeded":false,"displayWelcomeWizard":false,"isAdmin":true,"isDomainAdmi n":false,"isLicensed":true,"autoLoginToken":"","autoLoginUrl":"","isImpersonating":false,"canViewPassword s":false,"accessToken":"eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiJzaWRlcmFfaXZlcnRpeCIsIm5hbWUi OiJzaWRlcmFfaXZlcnRpeCIsInVzZXJuYW1lIjoic2lkZXJhX2l2ZXJ0aXgiLCJhZG1pbiI6IlRydWUiLCJyb290ZW1haWwiOiJzaWRlc mFfaXZlcnRpeCIsImNsYWltVmVyc2lvbiI6IjEiLCJyb2xlIjpbInVzZXIiLCJEb21haW5BZG1pbiIsIlN5c0FkbWluIl0sIkFkbWluSW QiOiJjYTBhNzYyYS1kZDRkLTQxZjEtYmQ1My04ODYwZjk2YTUwZDEiLCJDYW5JbXBlcnNvbmF0ZSI6IlRydWUiLCJJbXBlcnNvbmF0aW5 nIjoiRmFsc2UiLCJDYW5NYW5hZ2VEb21haW5zIjoiVHJ1ZSIsIkNhbk1hbmFnZVN5c3RlbVNldHRpbmdzIjoiVHJ1ZSIsIm5iZiI6MTYw Mzg5NDM3NCwiZXhwIjoxNjAzODk1Mjc0LCJpc3MiOiJzbWFydGVybWFpbCIsImF1ZCI6IioifQ.Vil9njw0XN8ecDFvUwwfyh63D_byqv QEZZ3Vz5SCywoT1SLf1BTh7OiAq27YcR9NaWTAwWlymToHfBLYjl0MCrB5VkUWLEWfvlpQS9OiYdUmts4Y2a33EMOB3PqWHqruiXaUcnu f0RpbZ2QL2fJJJRCDr-KT3b-db7Nku0xxsF-RmRoG_1pIsDPc_8RnyNWx0DDJTtF4nbzmNPfV3pNBWdNsnr0NcUzGHVIoGlzng32IUwWB ajnwGaki0hBuIGSIVHAgTi6uRa0dsR98QxgK9bWeMq5PB1tEWQscji54BQKvHwOAzYb0JmZ6U_XOqESCHUqnrgWMWHY9tj-ejL3avg"," refreshToken":"eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiJzaWRlcmFfaXZlcnRpeCIsIm5hbWUiOiJzaWRlc mFfaXZlcnRpeCIsInVzZXJuYW1lIjoic2lkZXJhX2l2ZXJ0aXgiLCJhZG1pbiI6IlRydWUiLCJyb290ZW1haWwiOiJzaWRlcmFfaXZlcn RpeCIsImNsYWltVmVyc2lvbiI6IjEiLCJyb2xlIjpbInVzZXIiLCJEb21haW5BZG1pbiIsIlN5c0FkbWluIl0sIkFkbWluSWQiOiJjYTB hNzYyYS1kZDRkLTQxZjEtYmQ1My04ODYwZjk2YTUwZDEiLCJDYW5JbXBlcnNvbmF0ZSI6IlRydWUiLCJJbXBlcnNvbmF0aW5nIjoiRmFs c2UiLCJDYW5NYW5hZ2VEb21haW5zIjoiVHJ1ZSIsIkNhbk1hbmFnZVN5c3RlbVNldHRpbmdzIjoiVHJ1ZSIsIm5iZiI6MTYwMzg5NDM3N CwiZXhwIjoxNjA5MDc4Mzc0LCJpc3MiOiJzbWFydGVybWFpbCIsImF1ZCI6IioifQ.OvJCGynvAnyIy1QU3cgNVyTZPRqgI3X9JgJNBBl yg9IXtCh2KXPAF0MoH7RncSi_LDZfHDl1sH0el_PTqeBwrsNSH3fQY48CZEHo_IVNuaqU2T7iAQqHtGgj9BGQLMOfv9MJwAKjChSr9kjC EqmJS0zmGlBveec1NZYAABouXX1nDrEAewwyGiiXOr1U6tfMQEVtQaPcokpDzPVFdS5o6W81HbfOkZ1DqY2flw2hqa80zhFl1iChLY320 sGEDn6b09LrV5lF9IK5EyWVIfziwIc3naogdzYxVZutFpKEipVktRWja5B-9KBqE2nkeR_H-icE1ddNVADipaMFnfXgaQ","accessTok enExpiration":"2020-10-28T14:27:54.5220622Z","username":"***user@","success":true,"resultCode":200 }

======> request send
GET https://webmail.***:443/api/v1/settings/sysadmin/spool-message-counts
Accept: application/json
Authorization: Bearer
User-Agent: centreon::plugins::backend::http::useragent

======> request send
GET https://webmail.***:443/api/v1/settings/sysadmin/spool-message-counts
Accept: application/json
Authorization: Bearer
User-Agent: centreon::plugins::backend::http::useragent

======> response done
HTTP/1.1 401 Unauthorized
Cache-Control: no-cache
Date: Wed, 28 Oct 2020 14:12:54 GMT
Pragma: no-cache
Server: Microsoft-IIS/10.0
Content-Length: 39
Content-Type: application/json; charset=utf-8
Expires: -1
Client-Date: Wed, 28 Oct 2020 14:12:54 GMT
Client-Peer: 46.234.233.53:443
Client-Response-Num: 4
Client-SSL-Cert-Issuer: /C=GB/ST=Greater Manchester/L=Salford/O=Sectigo Limited/CN=Sectigo RSA Domain Val idation Secure Server CA
Client-SSL-Cert-Subject: /CN=*.***removed***
Client-SSL-Cipher: ECDHE-RSA-AES256-GCM-SHA384
Client-SSL-Socket-Class: IO::Socket::SSL
Client-SSL-Warning: Peer certificate not verified

"Missing token in authorization header"

**Comment by garnier-quentin** [comment]
I'm blind....Could you test with last version ?

**Comment by rmorandell-pgum** [comment]
Now is working but doesn't show the different count names 

OK: All spools are ok | 'spool.messages.count'=10;;;0; 'spool.messages.count'=5000;;;0; 'spool.messages.count'=0;;;0; 'spool.messages.count'=50000;;;0; 'spool.messages.count'=0;;;0; 'spool.messages.count'=0;;;0; 'spool.messages.count'=0;;;0; 'spool.messages.count'=0;;;0; 'spool.messages.count'=2;;;0;

it should be

OK: Default count: 10 - Waiting : 2 - Spam : 0 - Virus : 0 - ThrottledUsers : 0 - ThrottledMailingLists : 0 - ThrottledDomains : 0 - Spool_limit : 50000 - Quarantine_limit : 5000 | 'default'=0;;;0; 'waiting'=0;;;0; 'spam'=0;;;0; 'virus'=0;;;0; 'throttledUsers'=0;;;0; 'throttledMailingLists'=0;;;0; 'throttledDomains'=0;;;0; 'spool_limit'=0;;;0; 'quarantine_limit'=0;;;0;

**Comment by rmorandell-pgum** [comment]
mode licenses show this error

UNKNOWN: Undefined subroutine &apps::smartermail::restapi::mode::licenses::catalog_status_threshold_ng called at /tmp/centreon-plugins-master/centreon/plugins/values.pm line 113.

**Comment by garnier-quentin** [comment]
It should be ok now

**Comment by rmorandell-pgum** [comment]
i have 2 questions for mode spools

OK: All spools are ok | 'default#spool.messages.count'=11;;;0; 'quarantine_limit#spool.messages.count'=5000;;;0; 'spam#spool.messages.count'=0;;;0; 'spool_limit#spool.messages.count'=50000;;;0; 'throttledDomains#spool.messages.count'=0;;;0; 'throttledMailingLists#spool.messages.count'=0;;;0; 'throttledUsers#spool.messages.count'=0;;;0; 'virus#spool.messages.count'=0;;;0; 'waiting#spool.messages.count'=3;;;0;

Can you cut of "#spool.messages.count" ? 

Actually i'm showing with my version of the plugin

image

****

in the new version the threshold are only generic ? 

 --warning-* --critical-*
            Thresholds. Can be: 'spool-messages'.

i was handling separated .. for example .. 

--warning-default=100 --warning-waiting=50 --warning-spam=20 --warning-virus=20  .....

unfortunately this is no longer possible

**Comment by rmorandell-pgum** [comment]
license mode is ok

OK: upgrade protection status is licensed - upgrade protection expires in 279 days | 'license.upgrade.protection.expires.days.count'=279;;;0;

services is ok

OK: All services are ok |

**Comment by garnier-quentin** [comment]
Yes you're right for thresholds. You can filter on name but you'll need to add many services. You could cut it with change-perfdata option.

**Comment by rmorandell-pgum** [comment]
> Yes you're right for thresholds. You can filter on name but you'll need to add many services. You could cut it with change-perfdata option.

could you tell me how we can cut that out with the change perfdata option? unfortunately i don't understand it based on the help

**Comment by garnier-quentin** [comment]
Like that: ```--change-perfdata='(.*)#.*,$1'```

**Pull request merged**
