### PR TITLE
Feature Ha Status for Synology Plugin

### PR DESCRIPTION
**Pull request by VinceBlood**
New mode to check Synology Cluster

### CODE REVIEW

**Comment by garnier-quentin** [comment]
Could you provide snmpwalk of that branch ? .1.3.6.1.4.1.6574.106

**Comment by VinceBlood** [comment]
Here the result :

[systel@SNMP ~]$ snmpwalk -v 2c -c public -m ALL 10.176.10.41 .1.3.6.1.4.1.6574.106
SNMPv2-SMI::enterprises.6574.106.1.0 = STRING: "NAS-1"
SNMPv2-SMI::enterprises.6574.106.2.0 = ""
SNMPv2-SMI::enterprises.6574.106.3.0 = INTEGER: 2
SNMPv2-SMI::enterprises.6574.106.4.0 = STRING: "NAS"
SNMPv2-SMI::enterprises.6574.106.5.0 = INTEGER: 1
SNMPv2-SMI::enterprises.6574.106.6.0 = INTEGER: 3
SNMPv2-SMI::enterprises.6574.106.7.0 = Gauge32: 0
SNMPv2-SMI::enterprises.6574.106.8.0 = Gauge32: 0

Some information

activeNodeName	- .1.3.6.1.4.1.6574.106.1.0
passiveNodeName - .1.3.6.1.4.1.6574.106.2.0
clusterAutoFailover - .1.3.6.1.4.1.6574.106.3.0
clusterName	- .1.3.6.1.4.1.6574.106.4.0
clusterStatus	- .1.3.6.1.4.1.6574.106.5.0 | normal(0),warning(1),critical(2),upgrading(3),processing(4)
heartbeatStatus - .1.3.6.1.4.1.6574.106.6.0 | normal(0),abnormal(1),disconnected(2),empty(3)
heartbeatTxRate - .1.3.6.1.4.1.6574.106.7.0 | Transfer speed of heartbeat in kilo-byte-per-second
heartbeatLatency - .1.3.6.1.4.1.6574.106.8.0 | Heartbeat latency in microseconds

**Comment by VinceBlood** [comment]
I propose to create heartbeatStatus

**Comment by garnier-quentin** [comment]
thanks for the PR. Could you test it ?

**Comment by VinceBlood** [comment]
Hi,

Actually, the Cluster is KO.

When using the new plugin, I have this :

OK: cluster status is '' [heartbeat status: ] [active node: ] [passive node: ]
'ha.heartbeat.latency.microseconds'=0us;;;0;

**Comment by garnier-quentin** [comment]
sorry. i fixed it. Could you test it ?

**Comment by VinceBlood** [comment]
It works !

HA Status |   | WARNING | 12s | WARNING: cluster status is 'warning' [heartbeat status: empty] [active node: NAS-1] [passive node: ]

**Pull request closed without merging**
