### PR TITLE
Sophos Email Appliance plugin

### PR DESCRIPTION
**Pull request by rk4an**

### CODE REVIEW

**Comment by garnier-quentin** [comment]
Could you give more information. The ES1000 is only for email security virtual/appliance ? Or for other Sophos products also ? 
Could you give me the result of following snmpwalk:
snmpwalk -v2c -c public -ObentU localhost 1.3.6 > sophos_es.snmpwalk

**Comment by rk4an** [comment]
[sophos_es.txt](https://github.com/centreon/centreon-plugins/files/675441/sophos_es.txt)

Is just for Sophos Email Appliance/Gateway: https://www.sophos.com/fr-fr/products/secure-email-gateway.aspx

Thanks,

**Comment by garnier-quentin** [comment]
Your ES is a virtual appliance no ?

**Comment by rk4an** [comment]
Yes mine is Virtual, but physical also exist

**Pull request closed without merging**
