### PR TITLE
Netapp, check snapmirrors state

### PR DESCRIPTION
**Pull request by CPbN**
Hi,

This PR improves Netapp snapmirrors check, checking their state in addition to their lag.

Thank you 👍

### CODE REVIEW

**Comment by CPbN** [comment]
May I ask you to review this and merge if it's OK for you ?
Many thanks !

**Comment by garnier-quentin** [comment]
Could you test it ?

**Comment by CPbN** [comment]
Many thanks Quentin !
You did not kept the filter-out on source volumes ?
https://github.com/centreon/centreon-plugins/pull/1342/files#diff-002875028676178aa324eaa7afd23cc2R123
This allows to quickly show if all snap targets are on the same host, and allows to generate only one alert (from the target host) when there's an issue, instead of 2.
Thx :+1:

**Comment by CPbN** [comment]
And of course I just tested the plugin, it works perfectly, thank you again :+1:

**Comment by garnier-quentin** [comment]
It will work even in source. I don't really see the point. I have done a last change. You can test it a last time ?

**Comment by CPbN** [comment]
Perfect, works as expected :+1: 
About source volumes, goal is to exclude them.
Think about a 2 nodes cluster, with the same monitoring on the 2 nodes.
You'll then monitor all snapmirrors twice.
Could be then interesting to exclude "source" volumes, so that :
- alerts will come from one node only ;
- you'll be able to know if all targets are on the same host (you expect 0 snapmirror on one of the 2 nodes).

**Comment by garnier-quentin** [comment]
Can add an option to filter on state so.

**Comment by CPbN** [comment]
Nice solution yes !

**Comment by garnier-quentin** [comment]
Add filter-status option

**Comment by CPbN** [comment]
Works perfectly, thank you @garnier-quentin !

**Pull request closed without merging**
