### PR TITLE
Add support of Sophos XG UTM

### PR DESCRIPTION
**Pull request by rk4an**

### CODE REVIEW

**Comment by rk4an** [comment]
Just see that a Cyberoam plugin was added few day ago. Note that Sophos XG is based on Cyberoam and will evoluting with maybe a new MIB from Sophos

https://github.com/centreon/centreon-plugins/releases/tag/20161014

**Comment by garnier-quentin** [comment]
You cannot use the cyberoam plugin instead ? If you are some modes missing, we can add it in cyberoam.
And then when a new mib coming, we'll add a plugin for Sophos XG

**Comment by rk4an** [comment]
We can do that but some oid of the Cyberoam mib doesn't work on Sophos (hit for example). I think we can already split it (cyberoam plugin for old device and sophos for new one)

**Comment by garnier-quentin** [comment]
Ok i see.

**Comment by rk4an** [comment]
I close this pull request and reopen a new one (problem with commit)

**Pull request closed without merging**
