### PR TITLE
HP Procurve: add spanningtree modes

### PR DESCRIPTION
**Pull request by joschi99**
discover and monitor spanning tree on hp procurve switches

### CODE REVIEW

**Comment by lucie-dubrunfaut** [comment]
Hello :)

 Could you please provide us with test data for this contribution for automated tests purpose ? (feel free to anonymize field that need it and also you can send it to my mail address also).

**Comment by joschi99** [comment]
send the snmpwalk by mail tu @lucie-dubrunfaut

**Comment by lucie-dubrunfaut** [comment]
Hello :)

Validation in progress internally here https://github.com/centreon/centreon-plugins/pull/5345 
Thanks again for your contribution :)

**Comment by lucie-dubrunfaut** [comment]
Released in [January 2025](https://github.com/centreon/centreon-plugins/releases/tag/plugins-20250114)

**Pull request closed without merging**
