### PR TITLE
Update systemdscstatus.pm

### PR DESCRIPTION
**Pull request by SavCent**
Add services name in error to the message

## Description

**PLEASE MAKE SURE THAT THE BRANCH PR INCLUDES JIRA TICKET ID** (_for centreon-internal_)

Please include a short resume of the changes and what is the purpose of PR. Any relevant information should be added to help:
* **QA Team** (Quality Assurance) with tests.
* **reviewers** to understand what are the stakes of the pull request.

**Fixes** # (issue)

## Type of change

- [ ] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software

## Target serie

- [ ] 22.04.x
- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x (master)

<h2> How this pull request can be tested ? </h2>

Please describe the **procedure** to verify that the goal of the PR is matched. Provide clear instructions so that it can be **correctly tested**.

Any **relevant details** of the configuration to perform the test should be added.

#### Community contributors & Centreon team

- [ ] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [ ] I have **rebased** my development branch on the base branch (master, maintenance).

### CODE REVIEW

**Comment by cgagnaire** [comment]
Hi,
The services' names are displayed by the prefix_sc_output function.
There is no need to do this.

**Comment by SavCent** [comment]
Hi,
i'm sorry but... no. in this case i don't have the service in critical state :

Command :
/usr/lib64/nagios/plugins/check_centreon_nrpe3 -H 10.19.141.143 -p 8084 -t 5 -u -c check_centreon_plugins -a 'os::linux::local::plugin' 'systemd-sc-status' ' --filter-name="" --exclude-name="^wes|^micro|^nano|^neo4j" --warning-status="" --critical-status="" --warning-total-running="" --critical-total-running="" --warning-total-failed="" --critical-total-failed="0" --warning-total-dead="" --critical-total-dead="" --warning-total-exited="" --critical-total-exited="" --verbose --use-new-perfdata'

Actually i've this service in error state (get it with --verbose):
Service 'insights-client.service' status : loaded/failed/failed [boot: static]

And the classic error message (without --verbose) is :
CRITICAL: Total Failed: 1

But we need something like :
CRITICAL: Total Failed: 1
Service 'insights-client.service' status : loaded/failed/failed [boot: static]

**Comment by cgagnaire** [comment]
Hi @SavCent,
That's because you squashed the default value for `--critical-status`.
Set it to `--critical-status='%{active} !~ /^active$/i'` or `--critical-status='%{active} =~ /^failed$/i` and it should work.

**Comment by SavCent** [comment]
it's work. thx !

**Pull request closed without merging**
