### PR TITLE
Add new Vyatta plugin

### PR DESCRIPTION
**Pull request by CPbN**
Hi,

This PR adds a new plugin to check Vyatta.
Rather simple.
The `keepalived` mode is more or less a copy of the `vrrp` one, with other OIDs of course.

Thank you :+1:

### CODE REVIEW

**Comment by Sims24** [comment]
Hi @CPbN thanks for this one ! 

Just wonder if the keepalived mode wouldn't deserve a dedicated directory in apps/keepalived. 

The fact that it's a ha/lb framework and that OIDs are part of a specific keepalived-mib, somebody could probably be interested in using the plugin but not necesserarly with a Vyatta equipement. 

What do you think ?

**Comment by Sims24** [comment]
Also, do you have the following OIDs populated for keepalived part ? 

.1.3.6.1.4.1.9586.100.5.3.3 (virtualServerTable)
and
.1.3.6.1.4.1.9586.100.5.3.4 (realServerTable)

**Comment by CPbN** [comment]
Thank you @Sims24 for your feedback.

> Just wonder if the keepalived mode wouldn't deserve a dedicated directory in apps/keepalived.

Good question.
There was a first try for the keepalived mode in #1466, well, for the VRRP instances info from the keepalived MIB I should say.
As the mode does let's say exactly what vrrp mode already does, but using different OIDs, I put it into the same `/snmp_standard/` folder.
One interested in this mode but for a device different than a Vyatta could easily integrate it into the `plugin.pm` file of its device.
We could also create a new `/apps/keepalived/` folder, up to you :)

> Also, do you have the following OIDs populated for keepalived part ?

Unfortunately no, on the 10 Vyatta I have, only `.1.3.6.1.4.1.9586.100.5.1` and `.2` are available.

Thank you :+1:

**Comment by Sims24** [comment]
>> There was a first try for the keepalived mode in #1466, well, for the VRRP instances info from the keepalived MIB I should say.

Ok so you need to create a dedicated plugin.pm and move the keepalived mode to a dedicated folder in apps/keepalived/snmp/ . 

>> As the mode does let's say exactly what vrrp mode already does, but using different OIDs, I put it into the same /snmp_standard/ folder.

snmp_standard is for all OIDs described by a RFC and should not contain anything related to a vendor_id, so please move it to the directory mentionned above. 

>> One interested in this mode but for a device different than a Vyatta could easily integrate it into the plugin.pm file of its device.

Yes ! 

Regards

**Comment by CPbN** [comment]
Just modified as you requested @Sims24, I then created a dedicated Keepalived plugin in #1505.
Thank you :+1:

**Comment by CPbN** [comment]
Well, as all remaining modes in this Vyatta plugin can be achieved using `os::linux::snmp::plugin`, I'm not sure it is really relevant...
In addition Vyatta is simply a Linux appliance...
Feel free then to tell me if we should rather close this...
Thank you !

**Comment by Sims24** [comment]
Yeah your right as far as I understand it only supports standard MIBs (https://support.rackspace.com/how-to/vyatta-snmp-and-logging/) so we will not create a dedicated directory for it.

**Pull request closed without merging**
