### PR TITLE
Show used and free values in the same probe

### PR DESCRIPTION
**Pull request by jben94**
Hi,

I open this PR adding the possibility to have the free space values in the same probe.
What is interesting when we want to make reports ....

### CODE REVIEW

**Comment by garnier-quentin** [comment]
Thanks but i can't accept it. The threshold won't be good. Moreover, it must be more global.

**Comment by jben94** [comment]
Hi,

Ok, I will review my changes. 
But can you add this option, to have both values in one check?

**Comment by garnier-quentin** [comment]
It's too specific.

**Comment by jben94** [comment]
So you have to check twice to have the used and free values in order to use usage rate (BI) reports?

**Comment by Sims24** [comment]
That's a main change. We know that it's important for a lot of our user, but we do not want to implement it in plugins. There's a better place ;) 

Thanks

**Pull request closed without merging**
