### PR TITLE
Better handle Blade/Flex temp thresholds

### PR DESCRIPTION
**Pull request by UrBnW**
Hi,

Strange case, but just faced it.

Thx 👍

### CODE REVIEW

**Comment by garnier-quentin** [comment]
Why we don't use the shutdown value and that's all ?

**Comment by UrBnW** [comment]
Because the device will shutdown, and it will be too late :)

**Comment by garnier-quentin** [comment]
That formula is weird: my $critical_mib = ($warning_mib + $2) / 2;
Why not:
$critical_mib = $2 - 5;
if ($critical_mib < $warning_mib) { $critical_mib = $warning_mib }

**Comment by UrBnW** [comment]
On the various devices I have, generally, `shutdown` temperature is `warning` temperature + 10.
I thought it was a good rule to have `CRITICAL` threshold set by default between these 2 values, so that you still have some time before the device will shutdown.

I faced however some devices where `shutdown` temperature == `warning` temperature.
Configuration error ? Perhaps, I don't know.
I then applied the -10 / -5 as generally seen on other devices.

If you're not please with `/ 2`, I would suggest :
```
$result->{hwInfoTemperatureWarn} =~ /^([.0-9]+)\s*C\s*\(Warn(?:ing)?\s*at\s*([.0-9]+)\s*C/i;
my $temperature = $1;
$result->{hwInfoTemperatureShut} =~ /^([.0-9]+)\s*C\s*\(Shutdown\s*at\s*([.0-9]+)\s*C/i;
$temperature = $1 if ($1 > $temperature);
my $critical_mib = $2 - 5;
my $warning_mib = $critical_mib - 5;
```

**Comment by UrBnW** [comment]
Let me know if you ant to go this way, I can quickly update this PR 👍

**Comment by garnier-quentin** [comment]
ok i understand

**Comment by UrBnW** [comment]
Thanks again for your reviews 😉

**Pull request merged**
