### PR TITLE
enh(watchguard) Add newlabels

### PR DESCRIPTION
**Pull request by UrBnW**
Hi,

Let's add some new labels for Watchguard devices.
This helps #1989.
Of course feel free if the name of the new labels are not correct !

Thx 👍

### CODE REVIEW

**Comment by UrBnW** [comment]
There's an issue with the `policyusage` and `system` modes, where perfdata unit is `b/s`, while OIDs return `Bytes`.
I made no correction, as I'm not sure what's the unit you prefer (seems to be `b/s`, but a few modes still use `B/s`). Thx !

**Comment by UrBnW** [comment]
While here, correct a unit issue in the `policyusage` and `system` modes, where traffic unit is set to bits (`unit => 'b/s'`), while OIDs return bytes.

**Comment by UrBnW** [comment]
And while here, remove the `diff => 1` option from the `total-connections` counter, `policy-usage` mode.
Seems like a typo, but I may be wrong...

**Comment by UrBnW** [comment]
Just reverted no more needed CPU new-labels, because CPU mode gets fully updated in #2069.

**Comment by garnier-quentin** [comment]
You can test it

**Comment by UrBnW** [comment]
Works perfectly, thx 👍

**Pull request closed without merging**
