### PR TITLE
Add oracle mode dataguard-lag

### PR DESCRIPTION
**Pull request by BenPls**
Hi,

Based on discussion in #1684, this is a proposal for a mode that checks Oracle dataguard lag.
It can give the number of 'missing' sequences and the time of the last applied sequence.
This is alos done for every dataguard destination (and you can filter as well).

### CODE REVIEW

**Comment by garnier-quentin** [comment]
Could you test the mode dataguard ?

**Comment by BenPls** [comment]
This is interesting!

Two small mistakes: 
'mrp_status' is twice here, and we're missing 'mrp_process'
https://github.com/centreon/centreon-plugins/blob/96a5d54cf1107cbc9c3c60e287b946b88385ad07/database/oracle/mode/dataguard.pm#L71

The closure should be 'custom_status_calc' (not 'catalog_status_calc')
https://github.com/centreon/centreon-plugins/blob/96a5d54cf1107cbc9c3c60e287b946b88385ad07/database/oracle/mode/dataguard.pm#L74


I'm not sure about the warning status default value.
AFAIK, those statuses are ok (maybe 'WAIT_FOR_GAP' isn't?).

**Comment by garnier-quentin** [comment]
Thanks it's fixed. I don't know for 'WAIT_FOR_GAP'.You want to put it in warning if WAIT_FOR_GAP ?

**Comment by BenPls** [comment]
IMHO, the default value should be '%{mrp_status}  !~ /APPLYING_LOG/i || (%{mrp_status}  =~ /WAIT_FOR_LOG/i and %{log_transport} =~ /LGWR/i'

**Comment by BenPls** [comment]
You didn't change the closure.
It should be: `closure_custom_calc => $self->can('custom_status_calc')`
(not 'catalog_status_calc').

**Comment by garnier-quentin** [comment]
Thanks. it should be ok now

**Comment by BenPls** [comment]
I apologize, I messed up with the ORs and the ANDs...

`'%{mrp_status} =~ /WAIT_FOR_LOG/i and %{log_transport} =~ /LGWR/i'` is the right default value.

**Comment by garnier-quentin** [comment]
fixed!

**Pull request closed without merging**
