### PR TITLE
Uptime, reduce chances to miss a reboot

### PR DESCRIPTION
**Pull request by CPbN**
Hi,

This PR reduces the chances to miss a reboot when uptime `--check-overload` is used.
I'm not sure why a +/- 50 seconds window would be required, which seems overkill.
A +/- 2.5 seconds window is IMO enough, and we should not miss any reboot then (as generally they last longer).

Many thanks :+1:

### CODE REVIEW

**Comment by garnier-quentin** [comment]
Because it can be timeout and other. So i prefer to let 50 seconds window. But we can add an option to set the window.

**Comment by CPbN** [comment]
That would say that SNMP answer has taken more than 50 seconds to come back from the device (well this is the only reason I see).
I've pushed another commit to harden `--check-overload` / correct another possible issue.

**Comment by CPbN** [comment]
I've just have submitted a new approach that should avoid missing reboots :)
It also solves one or two issues.
Thank you !

**Comment by garnier-quentin** [comment]
I have added an option you can use.

**Pull request closed without merging**
