### PR TITLE
Minor fix for kingdee eas ormrpc mode.

### PR DESCRIPTION
**Pull request by aladdinchan**

### CODE REVIEW

**Comment by garnier-quentin** [comment]
I have applied your change. But i think i will migrate your code soon (with counters class).

**Comment by aladdinchan** [comment]
Thanks you.

**Comment by garnier-quentin** [comment]
I will do a refactoring code. Could you provide me the output of all modes with --debug ? (can send me to my email please)

**Comment by garnier-quentin** [comment]
I begin the refactoring:
- 'httphandler' and 'muxhandler' are in the same mode: 'handlers'
- change the thresholds option for many modes

**Comment by aladdinchan** [comment]
Thank you very much for your work. 
I sent the debug output to your email, please check it.

**Pull request closed without merging**
