### PR TITLE
Mikrotik, add global error options

### PR DESCRIPTION
**Pull request by CPbN**
Hi,

This PR adds 2 new options to interfaces mode for Mikrotik, `--warning-errors` and `critical-errors`.
They allow to set thresholds for all errors at once.

The PR works, however I'm not sure this is the right way to do, so feel free to comment or modify.

Many thx :+1:

### CODE REVIEW

**Comment by garnier-quentin** [comment]
Could you test it ?

**Comment by CPbN** [comment]
Works as expected, many thanks for your review :+1:

**Comment by CPbN** [comment]
One issue though @garnier-quentin.
`output_error_template` is never used.
For example, instead of having :
`Packets In FCSError: 1.23%`
I get :
`Packets In Fcserror: 1.23%`
Whatever I put in `output_error_template`, it does not show in the error output.
Thx :+1:

**Comment by garnier-quentin** [comment]
error_template is not for that.

**Comment by CPbN** [comment]
Even of case of error (warning or critical), `custom_errors_output()` function is triggered to display the error message in the plugin short output.
Instead of using `output_error_template` which should (at least if I understand correctly) be used here.

**Comment by garnier-quentin** [comment]
It s not used for that. Output_error template is for example when you skip the counter

**Comment by CPbN** [comment]
OK, I finally managed to do what I want in #1544. Thank you for your answers.

**Pull request closed without merging**
