### PR TITLE
Linux os

### PR DESCRIPTION
**Pull request by kaileu**
Adding 2 Linux Checks.
The First is for Ubuntu/Debian derived OS which uses apt to update.
The 2nd is a Script to Check Linux Filesystems if there are mounted as read-only. (e.g. if the Storage has Problems in Virtualized Environments the Filesystem mount itself als read-only.)

### CODE REVIEW

**Comment by Sims24** [comment]
Hello, 

Thanks that's really interesting, I would prefer to keep os/linux as the standard checks for all distribtions, and create a dedicated directory for debian, suse, centos etc ... relying on common checks and providing some extra checks specific to each distrib. 

May ou adapt you're PR regarding to this ? Also, please check the indentation of the option declaration. 

Regards,

**Comment by kaileu** [comment]
I Split the PR to reflect the requested changes to split OS specific checks to seperate Files

**Comment by Sims24** [comment]
Ok thanks, I'm closing this one then

**Comment by kaileu** [comment]
@Sims24 Ther is one check left that checks if there are read-only Filesystems.
This one is equal on all Linux Systems maybe it was overlooked because for this one i dodn't make another PR

**Pull request closed without merging**
