### PR TITLE
add support for ACS8000 series (psu oid differs from ACS6000 series)

### PR DESCRIPTION
**Pull request by toxiczka**
This is mostly a copy of the ACS6000 module with few changes, to support ACS8000 series. Changes are of course the naming (6000 > 8000) and the new OIDs of the power supplys. Tested with all modes against an ACS8000 of course.

### CODE REVIEW

**Comment by garnier-quentin** [comment]
Could you provide mib files and full snmpwalk ? I will try to put in the same maybe.

**Comment by toxiczka** [comment]
Here you are! MIB Files are directly downloaded from vertiv.com.

[ACS8000-MIB.asn.txt](https://github.com/centreon/centreon-plugins/files/4421681/ACS8000-MIB.asn.txt)
[snmpwalk.log](https://github.com/centreon/centreon-plugins/files/4421714/snmpwalk.log)

**Comment by garnier-quentin** [comment]
Datas are missing in your snmpwalk. Need following branch:
.1.3.6.1.4.1.10418

**Comment by toxiczka** [comment]
Sorry, my mistake. I've updated the file in my previous comment with the branch you requested.

**Comment by garnier-quentin** [comment]
maybe we can add to check serial ports: status, traffic in/out ?

**Comment by toxiczka** [comment]
Would be great, but far above my skill level.

**Comment by garnier-quentin** [comment]
You can test the new mode

**Comment by toxiczka** [comment]
Have tested today. The new mode works - at least it shows the ports and 0 traffic. Since there seems to be no current activity on this device and I've no other than SNMP access to it, I cannot test if the traffic counters really work.

**Comment by garnier-quentin** [comment]
Thanks for the feedback. it should ;)

**Pull request merged**
