### PR TITLE
enh(mode): alyvix testcase date & freshness

### PR DESCRIPTION
**Pull request by thibaults-centreon**

### CODE REVIEW

**Comment by garnier-quentin** [comment]
Is 'testcase-date' useful ? We can display the last freshness in date (not seconds) for the output

**Comment by thibaults-centreon** [comment]
This counter aims to get this long output:
checking test case 'xxxxx'
    duration: 13390 ms, state: FAILED, last execution: 2020-11-12T14:21:18 (15s ago)
whereas the thresholds will only apply to the freshness value, so the "not ok" short output is more relevant in seconds.

Is there a more efficient way to do it ?

**Comment by garnier-quentin** [comment]
Like that:
```
{ label => 'testcase-freshness', display_ok => 0, set => {
                key_values => [ { name => 'freshness' }, { name => 'lastexec' },  { name => 'display' } ],
                closure_custom_output => $self->can('custom_date_output'),
                closure_custom_perfdata => sub { return 0; },
            }
        }
}
```

**Comment by garnier-quentin** [comment]
Could you add the perfdata ? It could be useful.

**Pull request closed without merging**
