### PR TITLE
improve processcount

### PR DESCRIPTION
**Pull request by cgagnaire**
- Add name lookup each time to make long output better. Also add PID.
```
# perl /usr/lib/centreon/plugins/centreon-plugins/centreon_plugins.pl --plugin=os::linux::snmp::plugin --mode=processcount --hostname=localhost --process-name='cbd' --regexp-name --verbose
OK: Number of current processes running: 2 | 'nbproc'=2;;;0;
Process 'cbd' [pid: 113682] [status: runnable]
Process 'cbd' [pid: 888] [status: runnable]
```

- Add memory and CPU usage to long output.
```
# perl /usr/lib/centreon/plugins/centreon-plugins/centreon_plugins.pl --plugin=os::linux::snmp::plugin --mode=processcount --hostname=localhost --process-name='cbd' --regexp-name --memory --cpu --verbose
OK: Number of current processes running: 2 - Total memory usage: 18.23 MB - Average memory usage: 9.12 MB - Total CPU usage: 0.00 % | 'nbproc'=2;;;0; 'mem_total'=19120128B;;;0; 'mem_avg'=9560064.00B;;;0; 'cpu_total'=0.00%;;;0;
Process 'cbd' [pid: 113682] [memory: 13.83 MB] [cpu: 0.00 %] [status: runnable]
Process 'cbd' [pid: 888] [memory: 4.40 MB] [cpu: 0.00 %] [status: runnable]
```

- Add the possibility to put thresholds on memory usage per processes. And show the problem in short output.
```
# perl /usr/lib/centreon/plugins/centreon-plugins/centreon_plugins.pl --plugin=os::linux::snmp::plugin --mode=processcount --hostname=localhost --process-name='cbd' --regexp-name --process-args='.*' --regexp-args --process-path='.*' --regexp-path --critical='2:2' --memory --warning-mem-each=12000000 --cpu --verbose
WARNING: Process 'cbd' [pid: 113682] memory usage: 13.83 MB | 'nbproc'=2;;2:2;0; 'mem_total'=19120128B;;;0; 'mem_avg'=9560064.00B;;;0; 'cpu_total'=0.65%;;;0;
Process 'cbd' [pid: 113682] [memory: 13.83 MB] [cpu: 0.47 %] [status: runnable] [args: /etc/centreon-broker/central-broker.xml] [path: /usr/sbin/cbd]
Process 'cbd' [pid: 888] [memory: 4.40 MB] [cpu: 0.18 %] [status: runnable] [args: /etc/centreon-broker/central-rrd.xml] [path: /usr/sbin/cbd]
```

- Rearrange options listing and improve help message.

### CODE REVIEW

**Comment by garnier-quentin** [comment]
Thanks but i can't accept it. By default, you set name and status. It was by design. We don't want to get too wide.

**Comment by cgagnaire** [comment]
- Removed the name lookup by default.
```
# perl /usr/lib/centreon/plugins/centreon-plugins/centreon_plugins.pl --plugin=os::linux::snmp::plugin --mode=processcount --hostname=localhost --process-name='cbd' --regexp-name --process-args='.*' --regexp-args --process-path='.*' --regexp-path --critical='1:1' --memory --warning-mem-each=12 --cpu --verbose
CRITICAL: Number of current processes running: 2 WARNING: Process '888' memory usage: 4.03 MB - Process '113682' memory usage: 12.97 MB | 'nbproc'=2;;1:1;0; 'mem_total'=17825792B;;;0; 'mem_avg'=8912896.00B;;;0; 'cpu_total'=0.00%;;;0;
Process '888' [memory: 4.03 MB] [cpu: 0.00 %] [status: runnable] [name: cbd] [args: /etc/centreon-broker/central-rrd.xml] [path: /usr/sbin/cbd]
Process '113682' [memory: 12.97 MB] [cpu: 0.00 %] [status: runnable] [name: cbd] [args: /etc/centreon-broker/central-broker.xml] [path: /usr/sbin/cbd]
```

- Changed top to show all pids of process.
```
# perl /usr/lib/centreon/plugins/centreon-plugins/centreon_plugins.pl --plugin=os::linux::snmp::plugin --mode=processcount --hostname=localhost --top --top-num=10 --top-size=0 --verbose
OK: Number of current processes running: 118 | 'nbproc'=118;;;0; 'top_mysqld'=326324224B;;;0; 'top_httpd'=321351680B;;;0; 'top_cbd'=59990016B;;;0; 'top_centreon_vmware'=56991744B;;;0; 'top_centreon_linux_'=29659136B;;;0; 'top_centengine'=17952768B;;;0; 'top_centreontrapd'=13295616B;;;0; 'top_sshd'=9621504B;;;0; 'top_rsyslogd'=5206016B;;;0; 'top_dsmd.pl'=4751360B;;;0;
Top 1 'mysqld' [pids: 16036] memory usage: 311.21 MB
Top 2 'httpd' [pids: 32534, 32114, 32535, 19963, 32536, 31536, 32538, 32539, 32533, 32540, 32537] memory usage: 306.46 MB
Top 3 'cbd' [pids: 2972, 2971] memory usage: 57.21 MB
Top 4 'centreon_vmware' [pids: 4559, 4558, 4550] memory usage: 54.35 MB
Top 5 'centreon_linux_' [pids: 12701, 12703] memory usage: 28.29 MB
Top 6 'centengine' [pids: 30000] memory usage: 17.12 MB
Top 7 'centreontrapd' [pids: 30258] memory usage: 12.68 MB
Top 8 'sshd' [pids: 8341, 4636, 4634, 32312] memory usage: 9.18 MB
Top 9 'rsyslogd' [pids: 1550] memory usage: 4.96 MB
Top 10 'dsmd.pl' [pids: 27301] memory usage: 4.53 MB
```

**Comment by cgagnaire** [comment]
Nope, I will.

**Comment by cgagnaire** [comment]
Tested against Windows 2016

```
# perl /usr/lib/centreon/plugins/centreon-plugins/centreon_plugins.pl --plugin=os::windows::snmp::plugin --mode=processcount --hostname=10.30.2.131 --snmp-version=2c --process-name='sql.*' --regexp-name --process-args='.*'  --regexp-args --process-path='.*' --regexp-path --memory --cpu --verbose
OK: Number of current processes running: 3 - Total memory usage: 354.80 MB - Average memory usage: 118.27 MB - Total CPU usage: 0.00 % | 'nbproc'=3;;;0; 'mem_total'=372031488B;;;0; 'mem_avg'=124010496.00B;;;0; 'cpu_total'=0.00%;;;0;
Process '2380' [memory: 298.11 MB] [cpu: 0.00 %] [status: running] [name: sqlservr.exe] [args:  -sMSSQLSERVER] [path: C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\Binn\]
Process '2368' [memory: 49.28 MB] [cpu: 0.00 %] [status: running] [name: sqlceip.exe] [args:  -Service ] [path: C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\Binn\]
Process '1600' [memory: 7.41 MB] [cpu: 0.00 %] [status: running] [name: sqlwriter.exe] [args: ] [path: C:\Program Files\Microsoft SQL Server\90\Shared\]
```

```
# perl /usr/lib/centreon/plugins/centreon-plugins/centreon_plugins.pl --plugin=os::windows::snmp::plugin --mode=processcount --hostname=10.30.2.131 --snmp-version=2c --top --top-num=10 --top-size=0 --verbose
OK: Number of current processes running: 56 | 'nbproc'=56;;;0; 'top_svchost.exe'=318169088B;;;0; 'top_sqlservr.exe'=312590336B;;;0; 'top_wsmprovhost.exe'=165027840B;;;0; 'top_ServerManager.exe'=135565312B;;;0; 'top_SearchUI.exe'=109989888B;;;0; 'top_dwm.exe'=93941760B;;;0; 'top_MsMpEng.exe'=91164672B;;;0; 'top_explorer.exe'=69857280B;;;0; 'top_ShellExperienceHost.exe'=54943744B;;;0; 'top_sqlceip.exe'=51769344B;;;0;
Top 1 'svchost.exe' [pids: 892, 300, 656, 1524, 848, 616, 96, 628, 272, 3844, 1404, 3568, 708, 912, 1632, 1548] memory usage: 303.43 MB
Top 2 'sqlservr.exe' [pids: 2380] memory usage: 298.11 MB
Top 3 'wsmprovhost.exe' [pids: 4396] memory usage: 157.38 MB
Top 4 'ServerManager.exe' [pids: 3424] memory usage: 129.29 MB
Top 5 'SearchUI.exe' [pids: 1540] memory usage: 104.89 MB
Top 6 'dwm.exe' [pids: 768, 1776] memory usage: 89.59 MB
Top 7 'MsMpEng.exe' [pids: 1696] memory usage: 86.94 MB
Top 8 'explorer.exe' [pids: 784] memory usage: 66.62 MB
Top 9 'ShellExperienceHost.exe' [pids: 3332] memory usage: 52.40 MB
Top 10 'sqlceip.exe' [pids: 2368] memory usage: 49.37 MB
```

**Comment by Sims24** [comment]
Thanks !

**Pull request merged**
