### PR TITLE
enh(netscaler) Add newlabels

### PR DESCRIPTION
**Pull request by UrBnW**
Hi,

Let's add some new labels for Netscaler devices.
This helps #1989.
Of course feel free if the name of the new labels are not correct !

Thx 👍

### CODE REVIEW

**Comment by UrBnW** [comment]
`cpu` mode is missing for now, as it needs a refactor.
We could copy `snmp_standard::mode::cpu` (updating OIDs of course) to have the 2 useful options `--warning-core` and `--critical-core`.

**Comment by garnier-quentin** [comment]
Need to do some refactor. But i have done some changes.

**Comment by UrBnW** [comment]
Many thanks @garnier-quentin.
One thing perhaps, seems like you forgot the `nlabel => 'storage.space.usage.bytes'` in `network/citrix/netscaler/snmp/mode/storage.pm` ?

**Comment by garnier-quentin** [comment]
I didn't forgot. Need to change the mode.

**Comment by UrBnW** [comment]
OK, I miss-understood :) Thx !

**Pull request closed without merging**
