### PR TITLE
New plugin ACR (Azure Container Registry)

### PR DESCRIPTION
**Pull request by matoy**
New plugin ACR (Azure Container Registry)

### CODE REVIEW

**Comment by Sims24** [comment]
Hello @matoy 

Thanks for this contribution (and the past ones), it means and helps a lot! 

I checked the supported metrics for ACR and I only found these: https://docs.microsoft.com/fr-fr/azure/azure-monitor/essentials/metrics-supported#microsoftcontainerregistryregistries. 

Maybe I'm not looking at the right place?

Thanks

**Comment by matoy** [comment]
indeed, it is not stated in the MS doc; but i can assure you the metric exists...
and the check works well in our centreon instance.

Capture d’écran 2021-07-16 145058

**Comment by Sims24** [comment]
Ok thanks for confirming that MS Doc is not up-to-date --'. 

We will merge it and maybe add few modes to get the percentage of successful run. WOuld it make sense? 

Regards

**Comment by matoy** [comment]
to be honest, i did write other modes because we didn't find any purpose to them but that might interest other people :)

**Comment by Sims24** [comment]
Ok, you're the user so if it doesn't make sense we will wait for somebody to ask for it. 

Thanks

**Review by Sims24 — APPROVED** [review]

**Pull request merged**
