### PR TITLE
new(plugin): add docker local/ssh plugin

### PR DESCRIPTION
**Pull request by cgagnaire**
Add Docker plugin using docker cli (local or SSH).
This way you don't use the restapi/containerd setup which exposes all endpoints to a root-like privilege.
But, because the cli scales values for statistics this is far less precise.

### CODE REVIEW

**Comment by garnier-quentin** [comment]
thanks @cgagnaire could you provide command and output examples ?

**Comment by cgagnaire** [comment]
```
# perl centreon_plugins.pl --plugin=cloud::docker::local::plugin --mode=container-usage --hostname=myhostname --ssh-username=sup --ssh-priv-key=/var/lib/centreon-engine/.ssh/sup --ssh-backend=libssh --sudo --filter-name=mariadb
OK: Container 'mariadb' cpu usage: 0.01 %, memory total: 7.79 GB used: 13.94 MB (0.17%) free: 7.78 GB (99.83%), disk read throughput: 0.00 B/s, disk write throughput: 0.00 B/s, traffic in: 0.00 b/s, traffic out: 0.00 b/s | 'mariadb#container.cpu.utilization.percentage'=0.01%;;;0;100 'mariadb#container.memory.usage.bytes'=14617149B;;;0;8364448808 'mariadb#container.disk.throughput.read.bytespersecond'=0B/s;;;0; 'mariadb#container.disk.throughput.write.bytespersecond'=0B/s;;;0; 'mariadb#container.traffic.in.bitspersecond'=0b/s;;;0; 'mariadb#container.traffic.out.bitspersecond'=0b/s;;;0;
```

```
# perl centreon_plugins.pl --plugin=cloud::docker::local::plugin --mode=container-status --hostname=myhostname --ssh-username=sup --ssh-priv-key=/var/lib/centreon-engine/.ssh/sup --ssh-backend=libssh --sudo --filter-name=mariadb
OK: Container 'mariadb' status is 'Up 28 days' 
```

```
# perl centreon_plugins.pl --plugin=cloud::docker::local::plugin --mode=list-containers --hostname=myhostname --ssh-username=sup --ssh-priv-key=/var/lib/centreon-engine/.ssh/sup --ssh-backend=libssh --sudo 
List containers: 
[id = 0b4af843a1ef] [name = mariadb] [status = Up 28 days]
[id = 54f023b32e40] [name = apache2] [status = Up 2 days]
[id = 432bde4f3452] [name = loki] [status = Up 1 days]
```

**Comment by garnier-quentin** [comment]
@cgagnaire have you tried the option [--format](https://docs.docker.com/engine/reference/commandline/stats/#format)  to have a json output ?

**Comment by cgagnaire** [comment]
Yes but the values are the same as the table format and its a "per line" json so there is no real gain.
And also sudoers conf does not seem to like curly braces so it would be counterproductive if you cannot define the all command in the conf.

**Comment by garnier-quentin** [comment]
The new PR: https://github.com/centreon/centreon-plugins/pull/4580

Could you test it ? I have done a minor change

**Pull request closed without merging**
