### PR TITLE
Please commit this modified expected-content.pm file.

### PR DESCRIPTION
**Pull request by sboulianne**
Can you commit this file please ?

This add warning and critical option for this check.

Thanks in advance.

[expectedcontent.txt](https://github.com/centreon/centreon-plugins/files/2349705/expectedcontent.txt)

### CODE REVIEW

**Comment by Sims24** [comment]
Hi @sboulianne just waiting for our co-maintainer to discuss few things on this one. Will come back to you when i got some fresh news ;)

**Comment by sboulianne** [comment]
Thanks! ;)

**Comment by cgagnaire** [comment]
This PR try to merge branch 2.7 to master. That's not anyone point :)
Please do it again.
Thanks.

**Comment by sboulianne** [comment]
Move it to the right branch and do what I ask!
I wrote to Sims24 directly.
Please reopen it!

**Pull request closed without merging**
