### PR TITLE
fix(output) set prct to 0 if max is 0

### PR DESCRIPTION
**Pull request by UrBnW**
Hi,

A simple fix to get a correct `0%` metric value when max value is `0`.

Thx 👍

### CODE REVIEW

**Comment by garnier-quentin** [comment]
Sorry but i don't want to apply (change the value) if there are no max (for invert).

**Comment by UrBnW** [comment]
Here we're in `percent` transform, not in `revert` ?

**Comment by garnier-quentin** [comment]
I know. I have done a mistake :)

**Comment by garnier-quentin** [comment]
You want to set 0% if you can percent because of max missing ?

**Comment by UrBnW** [comment]
Yes, I compute % value on some devices, where max value comes from the device.
Unfortunately, sometimes, this max value has not properly been set by the device administrators, thus returning 0.
I then would like the % value to be 0, instead of the original value (which is then not a %).

**Comment by UrBnW** [comment]
I think it's more correct / relevant...

**Comment by garnier-quentin** [comment]
I prefer to add an attribute to the function.

**Comment by UrBnW** [comment]
For completeness, here's my production example, without this PR :
```
--plugin=network::checkpoint::snmp::plugin --mode=connections --units=% --extend-perfdata='(.*),$1_prct,percent()'
OK: Connections: 9 | 'connections'=9con;;;0; 'connections_prct'=9con;;;0;
```

With this PR :
```
--plugin=network::checkpoint::snmp::plugin --mode=connections --units=% --extend-perfdata='(.*),$1_prct,percent()'
OK: Connections: 9 | 'connections'=9con;;;0; 'connections_prct'=0%;;;0;
```

**Comment by UrBnW** [comment]
> I prefer to add an attribute to the function.

Dont bother / waste time with this then, I'll make a fix in the plugin itself.

**Pull request closed without merging**
