### PR TITLE
implementation of PMG

### PR DESCRIPTION
**Pull request by steven04458**
setting up the API for Proxmox Mail Gateway

### CODE REVIEW

**Comment by garnier-quentin** [comment]
Thanks!

Could you provide --debug results for each mode please ?

**Comment by steven04458** [comment]
here is the command :
perl centreon_plugins.pl --plugin apps::proxmox::mg::restapi::plugin --mode virus --hostname Address_IP --api-username Admin --api-password 'totototo' --warning 1 --critical 2

Exemple api(virus):
OK: [Virus_in = '0'][Virus_out = '0'] | 'Virus_in'=0mail;0:1;0:2;0; 'Virus_out'=0mail;0:1;0:2;0;

Exemple api(count):
CRITICAL: [count_in = '4'][count_out = '1'] | 'mail_in'=4B;0:1;0:2;0; 'mail_out'=1B;0:1;0:2;0;

Exemple api(spam):
OK: [spam_in = '0'][spam_out = '0'] | 'spam_in'=0mail;0:1;0:2;0; 'spam_out'=0mail;0:1;0:2;0;

**Comment by garnier-quentin** [comment]
Please with --debug option.

**Comment by steven04458** [comment]
Exemple api(count): --debug option
---------------------
======> request send
GET https://relaismail.ville.fr:8006/api2/json/statistics/recent?timespan=120&hours=1
Accept: application/json
User-Agent: centreon::plugins::backend::http::useragent
Content-Type: application/x-www-form-urlencoded
Cookie: PMGAuthCookie=PMG:Admin@pmg:6040B881::kSWI35qXXgMnDb67Q8tYFEOSMhntRYhscqZsMKLtTbrPttfqnBra/BH4fur+R9azAMwFxG8JDHGf4UfywyfN0LrDoZWCr8Um9uwK8C3jHxs2Q3E6LucBi6N6bfkFQTPXu6B+8r4INVRchyNxK+I5jBT21m1Z23Ehg47Np/3viU0XEDh4td5qodfDiHf26FC/6+n4q+2OYGoSAiwKvgSwMzoA/35xfiGUaMitte61Ju2u+ISssJUtB9YIP+fpGJ81khGzaVJuBENhEYB7LKDcExiuUmF+4oS+Y1m07mH+rfnl+uAkFEIiV+XpvSo8EjG7PVHtriGSgXOsjXqUwhWsqg==

======> response done
HTTP/1.1 200 OK
Cache-Control: max-age=0
Connection: Keep-Alive
Date: Thu, 04 Mar 2021 11:28:23 GMT
Pragma: no-cache
Server: pve-api-daemon/3.0
Content-Length: 6602
Content-Type: application/json;charset=UTF-8
Expires: Thu, 04 Mar 2021 11:28:23 GMT
Client-Date: Thu, 04 Mar 2021 11:28:23 GMT
Client-Peer: 172.16.85.10:8006
Client-Response-Num: 1
Client-SSL-Cert-Issuer: /C=BE/O=GlobalSign nv-sa/CN=AlphaSSL CA - SHA256 - G2
Client-SSL-Cert-Subject: /OU=Domain Control Validated/CN=*.ville.fr
Client-SSL-Cipher: TLS_AES_256_GCM_SHA384
Client-SSL-Socket-Class: IO::Socket::SSL

{"data":[{"bytes_out":100540,"count":4,"ptimesum":20.646,"spam_out":0,"virus_in":0,"virus_out":0,"bytes_in":291073,"spam":0,"index":0,"count_out":2,"bytes":391613,"timespan":120,"virus":0,"time":1614853703,"spam_in":0,"count_in":2},{"timespan":120,"count_out":4,"bytes":3787069,"virus":0,"time":1614853823,"spam_in":0,"count_in":4,"bytes_out":3390103,"count":8,"ptimesum":47.717,"virus_in":0,"spam_out":0,"virus_out":0,"spam":0,"bytes_in":396966,"index":1},{"spam_out":0,"ptimesum":67.786,"virus_in":0,"count":8,"bytes_out":22305,"spam":0,"bytes_in":2607638,"virus_out":0,"index":2,"timespan":120,"count_out":2,"bytes":2629943,"count_in":6,"spam_in":0,"virus":0,"time":1614853943},{"timespan":120,"bytes":107930,"count_out":1,"count_in":1,"spam_in":0,"virus":0,"time":1614854063,"index":3,"ptimesum":11.961,"virus_in":0,"spam_out":0,"bytes_out":2886,"count":2,"spam":0,"bytes_in":105044,"virus_out":0},{"count_in":5,"spam_in":1,"virus":0,"time":1614854183,"timespan":120,"bytes":366459,"count_out":1,"spam":1,"bytes_in":252429,"virus_out":0,"ptimesum":50.642,"virus_in":0,"spam_out":0,"bytes_out":114030,"count":6,"index":4},{"count_in":2,"spam_in":0,"virus":0,"time":1614854303,"bytes":502200,"count_out":0,"timespan":120,"index":5,"bytes_in":502200,"spam":0,"virus_out":0,"ptimesum":19.121,"virus_in":0,"spam_out":0,"bytes_out":0,"count":2},{"count_out":2,"bytes":47545,"timespan":120,"spam_in":0,"virus":0,"time":1614854423,"count_in":1,"count":3,"bytes_out":10844,"spam_out":0,"ptimesum":10.253,"virus_in":0,"virus_out":0,"spam":0,"bytes_in":36701,"index":6},{"timespan":120,"count_out":1,"bytes":513166,"count_in":3,"virus":0,"spam_in":0,"time":1614854543,"ptimesum":32.196,"virus_in":0,"spam_out":0,"count":4,"bytes_out":124087,"bytes_in":389079,"spam":0,"virus_out":0,"index":7},{"count_in":1,"virus":0,"time":1614854663,"spam_in":1,"timespan":120,"bytes":6250,"count_out":0,"bytes_in":6250,"spam":1,"virus_out":0,"virus_in":0,"ptimesum":8.542,"spam_out":0,"count":1,"bytes_out":0,"index":8},{"index":9,"virus_out":0,"spam":0,"bytes_in":109010,"bytes_out":1324252,"count":5,"ptimesum":36.479,"virus_in":0,"spam_out":0,"virus":0,"spam_in":0,"time":1614854783,"count_in":3,"bytes":1433262,"count_out":2,"timespan":120},{"index":10,"bytes_in":1476819,"spam":0,"virus_out":0,"ptimesum":19.77,"virus_in":0,"spam_out":0,"bytes_out":444605,"count":3,"count_in":2,"spam_in":0,"virus":0,"time":1614854903,"count_out":1,"bytes":1921424,"timespan":120},{"index":11,"spam_out":0,"virus_in":0,"ptimesum":31.991,"count":4,"bytes_out":6301,"spam":0,"bytes_in":111920,"virus_out":0,"timespan":120,"count_out":1,"bytes":118221,"count_in":3,"virus":0,"spam_in":0,"time":1614855023},{"bytes":1460149,"count_out":4,"timespan":120,"virus":0,"time":1614855143,"spam_in":0,"count_in":3,"count":7,"bytes_out":1393151,"virus_in":0,"spam_out":0,"ptimesum":27.028,"virus_out":0,"bytes_in":66998,"spam":0,"index":12},{"count_in":1,"time":1614855263,"virus":0,"spam_in":0,"timespan":120,"bytes":1591607,"count_out":1,"spam":0,"bytes_in":66541,"virus_out":0,"spam_out":0,"ptimesum":13.053,"virus_in":0,"bytes_out":1525066,"count":2,"index":13},{"virus_out":0,"bytes_in":47254,"spam":0,"count":2,"bytes_out":700138,"spam_out":0,"virus_in":0,"ptimesum":11.521,"index":14,"virus":0,"spam_in":0,"time":1614855383,"count_in":1,"timespan":120,"bytes":747392,"count_out":1},{"count":5,"bytes_out":0,"ptimesum":47.042,"virus_in":0,"spam_out":0,"virus_out":0,"bytes_in":4654606,"spam":1,"index":15,"count_out":0,"bytes":4654606,"timespan":120,"virus":0,"time":1614855503,"spam_in":1,"count_in":5},{"virus_in":0,"ptimesum":20.558,"spam_out":0,"bytes_out":98294,"count":5,"bytes_in":1546053,"spam":0,"virus_out":0,"index":16,"count_out":3,"bytes":1644347,"timespan":120,"count_in":2,"time":1614855623,"virus":0,"spam_in":0},{"index":17,"count":4,"bytes_out":152313,"spam_out":0,"ptimesum":36.142,"virus_in":0,"virus_out":0,"bytes_in":1537959,"spam":0,"bytes":1690272,"count_out":1,"timespan":120,"spam_in":0,"virus":0,"time":1614855743,"count_in":3},{"bytes":51716,"count_out":0,"timespan":120,"count_in":3,"virus":0,"time":1614855863,"spam_in":0,"index":18,"virus_in":0,"ptimesum":32.472,"spam_out":0,"count":3,"bytes_out":0,"bytes_in":51716,"spam":0,"virus_out":0},{"index":19,"spam":1,"bytes_in":481822,"virus_out":0,"spam_out":0,"virus_in":0,"ptimesum":52.142,"bytes_out":0,"count":5,"count_in":5,"spam_in":1,"virus":0,"time":1614855983,"bytes":481822,"count_out":0,"timespan":120},{"count_in":5,"virus":0,"time":1614856103,"spam_in":0,"timespan":120,"count_out":1,"bytes":189217,"bytes_in":186311,"spam":0,"virus_out":0,"virus_in":0,"ptimesum":57.66,"spam_out":0,"count":6,"bytes_out":2906,"index":20},{"bytes":551430,"count_out":2,"timespan":120,"count_in":1,"spam_in":0,"virus":0,"time":1614856223,"index":21,"ptimesum":9.543,"spam_out":0,"virus_in":0,"count":3,"bytes_out":543363,"spam":0,"bytes_in":8067,"virus_out":0},{"bytes_out":0,"count":1,"spam_out":0,"virus_in":0,"ptimesum":12.58,"virus_out":0,"spam":0,"bytes_in":61315,"index":22,"count_out":0,"bytes":61315,"timespan":120,"time":1614856343,"virus":0,"spam_in":0,"count_in":1},{"timespan":120,"count_out":0,"bytes":20998,"count_in":3,"spam_in":1,"virus":0,"time":1614856463,"ptimesum":28.876,"virus_in":0,"spam_out":0,"count":3,"bytes_out":0,"spam":1,"bytes_in":20998,"virus_out":0,"index":23},{"spam":0,"bytes_in":191170,"virus_out":0,"spam_out":0,"ptimesum":20.97,"virus_in":0,"count":2,"bytes_out":0,"index":24,"count_in":2,"spam_in":0,"virus":0,"time":1614856583,"timespan":120,"count_out":0,"bytes":191170},{"bytes_out":52930,"count":1,"virus_in":0,"ptimesum":0.096,"spam_out":0,"virus_out":0,"spam":0,"bytes_in":0,"index":25,"count_out":1,"bytes":52930,"timespan":120,"virus":0,"spam_in":0,"time":1614856703,"count_in":0},{"ptimesum":0,"spam_out":0,"virus_in":0,"bytes_out":0,"count":0,"spam":0,"bytes_in":0,"virus_out":0,"index":26,"bytes":0,"count_out":0,"timespan":120,"count_in":0,"time":1614856823,"spam_in":0,"virus":0},{"index":27,"bytes_in":40470,"spam":0,"virus_out":0,"ptimesum":9.92,"virus_in":0,"spam_out":0,"bytes_out":0,"count":1,"count_in":1,"time":1614856943,"virus":0,"spam_in":0,"timespan":120,"count_out":0,"bytes":40470},{"count_out":0,"bytes":72837,"timespan":120,"count_in":2,"spam_in":0,"virus":0,"time":1614857063,"index":28,"ptimesum":26.553,"virus_in":0,"spam_out":0,"count":2,"bytes_out":0,"spam":0,"bytes_in":72837,"virus_out":0},{"virus_out":0,"spam":0,"bytes_in":0,"bytes_out":0,"count":0,"virus_in":0,"ptimesum":0,"spam_out":0,"index":29,"time":1614857183,"spam_in":0,"virus":0,"count_in":0,"count_out":0,"bytes":0,"timespan":120}]}

**Comment by garnier-quentin** [comment]
Could you provide it for all modes please ? (you can send it by email in files: qgarnier@centreon.com).

**Comment by steven04458** [comment]
For virus and spam modes, the result will be the same as the account because it uses the same source.

**Comment by garnier-quentin** [comment]
I have done some refactoring. Could you test with that archive ?
https://github.com/centreon/centreon-plugins/archive/fix-2633.zip

The mode is: ```--mode=mail```

**Comment by steven04458** [comment]
I tested it and it works, here is the result I got.

OK: Mail statistics are ok | 'mails.incoming.count'=808;;;0; 'mails.outgoing.count'=322;;;0; 'mails.traffic.in.bytespersecond'=3387.59B/s;;;0; 'mails.traffic.out.bytespersecond'=1888.30B/s;;;0; 'mails.spam.incoming.count'=129;;;0; 'mails.spam.outgoing.count'=0;;;0; 'mails.virus.incoming.count'=0;;;0; 'mails.virus.outgoing.count'=0;;;0;

**Comment by garnier-quentin** [comment]
Thanks for the feedback. I have also added the mode ```version```. It should be ok now ;)

**Pull request closed without merging**
