### PR TITLE
Fixed infinite loop on multiple page output

### PR DESCRIPTION
**Pull request by alfredosilvestre-natixis**
Hello,

On using this plugin when it returns multiple pages, it will stay in an infinite loop as neither the page nor the path gets changed.

This is one solution, I don't know if it is what you have in mind, we can also extract the page number from the "next" url.

### CODE REVIEW

**Comment by garnier-quentin** [comment]
Thanks for the PR. Could you test it with last commit ?

**Comment by alfredosilvestre-natixis** [comment]
Yup it is working as well, thanks

**Comment by alfredosilvestre-natixis** [comment]
Hello,

In fact we just had an issue when you only have one page so the json result does not have "next" defined and it remains in an infinite loop.

Example:
{"count":4,"next":null,"previous":null,
....

**Comment by garnier-quentin** [comment]
With my commit, if next is not defined, it quits the loop. Could you provide the --debug ?

**Comment by alfredosilvestre-natixis** [comment]
Yes, of course, see attached.

I saw that if the next is not defined and it should work, however I think there is something on the decoded content.

[debug_output.txt](https://github.com/centreon/centreon-plugins/files/5332766/debug_output.txt)

**Comment by garnier-quentin** [comment]
I have done a patch. Could you test it ?

**Comment by alfredosilvestre-natixis** [comment]
Besides the extra "if" on line 170 it seems to be working 😄

**Comment by garnier-quentin** [comment]
Thanks. It should be fixed

**Pull request closed without merging**
