### PR TITLE
(plugin) storage::wd::nas::snmp - new

### PR DESCRIPTION
**Pull request by garnier-quentin**

### CODE REVIEW

**Review by itoussies — APPROVED** [review]

**Comment by joschi99** [comment]
Some news when you will publish this pull request? Is working fine for EX4100 and other WD devices

**Comment by lucie-dubrunfaut** [comment]
Hello @joschi99 :)
I'm not sure to understand what you are meaning about publishing this pull request because for me it's already merged in develop branch (see [here](https://github.com/centreon/centreon-plugins/tree/develop/src/storage/wd/nas/snmp)) ?

**Comment by joschi99** [comment]
If you are looking your develop branch the changes are still not available.
image

**Comment by lucie-dubrunfaut** [comment]
If I take a look at the files created in this PR it's exactly the same content at the same lines than your screenshot 
image
_hardware.pm line 117 to 145_
So I'm confuse but I don't see the difference you are asking to publish ?

**Pull request merged**
