### PR TITLE
Add mode list-tabelspaces with usage for discovery

### PR DESCRIPTION
**Pull request by rmorandell-pgum**
New mode "list-tablespaces" with usages for discovery

### CODE REVIEW

**Comment by garnier-quentin** [comment]
Thanks. I added the mode. Could you test it ?

**Comment by rmorandell-pgum** [comment]
Hi,

i tested it now with your changes. Unfortunately it does not work anymore. The following error message:

perl centreon_plugins.pl --plugin=database::oracle::plugin --hostname=xxx --port=1521 --sid=AHBUCH --username='ivertix' --password=xxx --mode=list-tablespaces --disco-show

 Can't call method "fetchall_arrayref" on an undefined value at /usr/lib/centreon/plugins/database/oracle/mode/listtablespaces.pm line 271.

It could be the connection ?!?

Using my commit its working

 perl centreon_plugins.pl --plugin=database::oracle::plugin --hostname=xxx --port=1521 --sid=AHBUCH --username='ivertix' --password=xxx --mode=list-tablespaces --disco-show
<?xml version="1.0" encoding="utf-8"?>
<data>
  <label free="9046917120" name="adhoc" used="16722886656" prct_used="64.8933410644531" total="25769803776"/>
  <label free="6442254336" name="ahrdemo" used="196608" prct_used="0.0030517578125" total="6442450944"/>
  <label free="1567227904" name="expdp" used="2727739392" prct_used="63.5101318359375" total="4294967296"/>
  <label free="5207621632" name="f00" used="17340956672" prct_used="76.9048781622024" total="22548578304"/>
  <label free="1567555584" name="sysaux" used="579928064" prct_used="27.0050048828125" total="2147483648"/>
  <label free="1158873088" name="system" used="2062352384" prct_used="64.0238444010417" total="3221225472"/>
  <label free="8589934592" name="temp" used="0" prct_used="0" total="8589934592"/>
  <label free="2147418112" name="undotbs1" used="65536" prct_used="0.0030517578125" total="2147483648"/>
  <label free="2147418112" name="users" used="65536" prct_used="0.0030517578125" total="2147483648"/>
</data>

**Comment by garnier-quentin** [comment]
I have done the patch. You could test it again ?

**Comment by rmorandell-pgum** [comment]
Ok now it's working fine. Thanks a lot !!

**Comment by rmorandell-pgum** [comment]
Hi Quentin,
i have a problem with the new list-tablespaces plugin. On my customers system are over 260 tablespaces. When i'm using the plugin that i created (based on query from old tablespace-usage plugin. Just this from my pull request) i'm getting the list in a few ms without problem. When i'm using the latest version of the plugin it doesn't work with a large number of tablespaces. With a small list its working. The tablespace-usage has the same problem now on this system, too. The old plugin is working. 
Have you an idea what can happens ?

**Comment by garnier-quentin** [comment]
Maybe i can put it back the request with the new view. But with that view, undo tablespace have wrong values.

**Pull request closed without merging**
