### PR TITLE
Add list-storage mode for windows NSClient

### PR DESCRIPTION
**Pull request by Tpo76**

### CODE REVIEW

**Comment by garnier-quentin** [comment]
It woul be better to create a dll in nsclient i think ;)

**Comment by Tpo76** [comment]
Does it make sense to create dll in NSClient to have diso-show option ?
If yes, I can check that

**Comment by garnier-quentin** [comment]
An dll to add centreon commands (not disco show option).

**Comment by Sims24** [comment]
Looks good to me. I merge it. Please think about centreon_plugins.exe building and also discovery rules.

**Pull request merged**
