### PR TITLE
(plugin) storage::dell::powerstore::restapi - mode alerts add acknowl…

### PR DESCRIPTION
**Pull request by garnier-quentin**
…edged attributes

### CODE REVIEW

**Comment by Sims24** [comment]
Hi @Hbitvof, 

The default behaviour doesn't change: 

```
            warning_default => '%{severity} =~ /minor/i',
            critical_default => '%{severity} =~ /major|critical/i',
```

You have to user for example --warning-status='%{severity} =~ /minor/i && %{acknowledged} =~ /^no$/'

**Comment by Hbitvof** [comment]
> Hi @Hbitvof,
> 
> The default behaviour doesn't change:
> 
> ```
>             warning_default => '%{severity} =~ /minor/i',
>             critical_default => '%{severity} =~ /major|critical/i',
> ```
> 
> You have to use for example --warning-status='%{severity} =~ /minor/i && %{acknowledged} =~ /^no$/'

What is the example exactly doing? We want to see all warnings except the acknowledged ones.

**Comment by Sims24** [comment]
It does that. Trigger a warning only if alarm is minor and not acknowledged. 

You can follow the same logic with the --critical-status option value.

**Comment by Hbitvof** [comment]
That's working, thanks!

**Pull request merged**
