### PR TITLE
Added missing job-status options

### PR DESCRIPTION
**Pull request by alfredosilvestre-natixis**
Hello,

While trying to execute the commands I noticed that the job-status options were missing even though they were in the documentation.

This will add the options on the plugin and use them in the appropriate place.

Thank you for your time.

### CODE REVIEW

**Comment by garnier-quentin** [comment]
It's not missing. the plugin should work. What is your problem ? threshold are not working ? (because it should)

**Comment by alfredosilvestre-natixis** [comment]
The issue is with executing the plugin, the options "unknown-job-status", "warning-job-status" and "critical-job-status" are not recognized

Example command line:

$ /usr/lib/centreon/plugins/centreon_ansible_tower.pl --plugin=apps::automation::ansible::tower::plugin --mode=hosts --hostname='awx.intranet' --username='admin' --password=*** --custommode='api' --port 443 --proto 'https' --filter-name='' --unknown-job-status='%{last_job_status} =~ /default/' --warning-job-status='' --critical-job-status='%{last_job_status} =~ /failed/' --warning-total='' --critical-total='' --warning-failed='' --critical-failed='' --verbose
Unknown option: unknown-job-status at /usr/lib/centreon/plugins/centreon/plugins/alternative/Getopt.pm line 67.

**Comment by garnier-quentin** [comment]
Do you have sub-directories in /usr/lib/centreon/plugins/ ?

**Comment by alfredosilvestre-natixis** [comment]
Yes, it has the same structure as the github repository.

image

For information, it probably does not make a difference, but I tested with 19.04.

**Comment by garnier-quentin** [comment]
That's the issue. Please remove sub-directories.

**Comment by alfredosilvestre-natixis** [comment]
But that is where the plugins are..

**Comment by garnier-quentin** [comment]
You should put github plugin in one other directory. Otherwise it's not a plugin issue.

**Comment by alfredosilvestre-natixis** [comment]
But have you tested the command line ?

If I use the centreon_plugins.pl, not the fatpacked centreon_ansible_tower.pl the issue is the same.

We have all our plugins in that directory and every other plugin works.

See for example line 71 in apps/automation/ansible/tower/mode/hosts.pm, the argument "--unknown-job-status" was not being taken into account

**Comment by garnier-quentin** [comment]
Try with the last version here (new directory). It will work

**Comment by alfredosilvestre-natixis** [comment]
In fact we did not have the folder "centreon/plugins/" updated, it works now with both methods 👍 

Thank you

**Pull request closed without merging**
