### PR TITLE
+ bugfix iDrac > 6 

### PR DESCRIPTION
**Pull request by Gilum**
bugfix https://github.com/centreon/centreon-plugins/commit/aeb31bbc3355ad0e0a667500acb2e5370537e96e

### CODE REVIEW

**Comment by garnier-quentin** [comment]
Why the following change ?

**Comment by Gilum** [comment]
./centreon_plugins.pl --plugin=hardware::server::dell::idrac::snmp::plugin --mode=global-status --hostname=[idrac6]
OK: Overall global status is 'ok' |
./centreon_plugins.pl --plugin=hardware::server::dell::idrac::snmp::plugin --mode=global-status --hostname=[idrac7]
OK: Overall global status is 'ok' |

drsGlobalSystemStatus exist always in idrac7, globalSystemStat not exist in idrac6


./centreon_plugins.pl --plugin=hardware::server::dell::idrac::snmp::plugin --mode=global-status --hostname=[idrac6]
OK: Overall global status is 'ok' |

./centreon_plugins.pl --plugin=hardware::server::dell::idrac::snmp::plugin --mode=global-status --hostname=[idrac7]
OK: Overall global status is 'ok' - Overall storage status is 'ok' |

**Comment by garnier-quentin** [comment]
seems messy for what does what :)
You prefer to test 'globalSystemStat' first ?

**Comment by Gilum** [comment]
new commit https://github.com/Gilum/centreon-plugins/commit/efef232d62936a41afbeb2e45a2f0dce3d23f802

**Comment by garnier-quentin** [comment]
thanks

**Pull request merged**
