### PR TITLE
Improve snmp-autoreduce in case device does not reply tooBig

### PR DESCRIPTION
**Pull request by CPbN**
Hi,

I faced issue described in #880 :
`--plugin=storage::netapp::snmp::plugin --mode=volumeoptions` asks for info for let's say 25 volumes.
The Netapp device replies but only for the X first volumes (certainly until a fixed packet size is reached, around 4000 bytes as per my tests).
There is no SNMP error : `$self->{session}->get($vb)` in `get_leef()` does not return error.
But then some elements are missing in the answer, which then leads to errors (and undefined values) described in #880.

I'm then quite surprised that the Netapp device does not reply with the `tooBig` error message.
This PR then fixes this when `--snmp-autoreduce` is used.

I wonder if we would have to apply the same fix into `get_table()` and `get_multiple_table()`.
According to their loop through `@$vb` I would say no as `${$entry}[2]` is checked there without testing `@{$entry}` length.
But perhaps this is an issue...

Thank you :+1:

### CODE REVIEW

**Comment by CPbN** [comment]
In reality it's even worse.
Let's say you ask for 25 volumes.
And you have `--subsetleef=20`.
You'll get an answer for the 7 first volumes (UDP packet around 4000 bytes), and the 5 last ones (second SNMP request).
You won't get info for volumes 8 to 20 (part of the first SNMP request).

**Comment by garnier-quentin** [comment]
It shouldn't work that way. Could you do a teamviewer together tomorrow ?

**Comment by CPbN** [comment]
Sure !

**Comment by garnier-quentin** [comment]
Fixed 3c48822071cecaf60a1357885e17fa5c86d442a4

**Comment by CPbN** [comment]
Many thanks :+1:

**Pull request closed without merging**
