### PR TITLE
Add thresholds on http expected-string extracted value

### LINKED ISSUE #1211: [apps/protocols/http] Thresholds on captured value in --expected-string
Hi,

In `apps::protocols::http::plugin`, when looking for content using `--mode=expected-content`, would be nice to be able define thresholds on a capture value in the expected string.

Let's assume a web page contains the following :
`Node: 1, Status: OK, Ping: 10, Connections: 34, Load: 100`

And we want less than 100 connections.

The following would do what we want :
`--expected-string=",Connections: ([0-9]*)," --captured-warning=80 --captured-critical=100`
_Note the captured value in the regexp._

Of course the captured value would go in performance data.

Thank you very much :+1:

### PR DESCRIPTION
**Pull request by CPbN**
Hi,

This PR closes #1211.

It adds 2 new thresholds in `apps::protocols::http::plugin`, `expected-content` mode.

Let's assume a web page contains the following :
`Node: 1, Status: OK, Ping: 10, Connections: 34, Load: 100`

And we want less than 100 connections.

We can now do the following :
`--expected-string=",Connections: ([0-9]*)," --warning-extracted=80 --critical-extracted=100`

Thank you very much :+1:

### CODE REVIEW

**Comment by CPbN** [comment]
Hi @cgagnaire, may we have your feedback when you'll have some time (perhaps based on discussion in #1211).
Really looking forward to see this merged :)
Thank you very much :+1:

**Comment by CPbN** [comment]
Anything preventing from merging this ? :)
Many thanks :+1:

**Comment by garnier-quentin** [comment]
You can test it ?

**Comment by CPbN** [comment]
It works perfectly, thank you very much !

**Pull request closed without merging**
