### PR TITLE
Improve tha databassize calculation

### PR DESCRIPTION
**Pull request by Dodofox**
Using maxsize (with autoextend if existing) and real size. not original procstock.

I think you will have to correct my English :D 

Dorian Renard

### CODE REVIEW

**Comment by garnier-quentin** [comment]
Does it work with all MSSQL server version ?

**Comment by garnier-quentin** [comment]
I think we can approve more. Could you test that following request work ?
```
select db_name(d.dbid) as db_name,
ceiling(sum(case when u.segmap != 4 then u.size/1048576.*@@maxpagesize end )) as data_size,
ceiling(sum(case when u.segmap != 4 then size - curunreservedpgs(u.dbid, u.lstart, u.unreservedpgs) end).*@@maxpagesize) as data_used,
ceiling(100 * (1 - 1.0 * sum(case when u.segmap != 4 then curunreservedpgs(u.dbid, u.lstart, u.unreservedpgs) end) / sum(case when u.segmap != 4 then u.size end))) as data_used_pct,
ceiling(sum(case when u.segmap = 4 then u.size/1048576.*@@maxpagesize end)) as log_size,
ceiling(sum(case when u.segmap = 4 then u.size/1048576.*@@maxpagesize end) - lct_admin("logsegment_freepages",d.dbid).*@@maxpagesize) as log_used,
ceiling(100 * (1 - 1.0 * lct_admin("logsegment_freepages",d.dbid) / sum(case when u.segmap in (4, 7) then u.size end))) as log_used_pct 
from master..sysdatabases d, master..sysusages u
where u.dbid = d.dbid  and d.status not in (256,4096)
group by d.dbid
order by db_name(d.dbid)
```

**Comment by Dodofox** [comment]
Hi, 

I can try it only next week on Wednesday. I'll keep you informed !!

**Comment by garnier-quentin** [comment]
Thanks a lot

**Comment by garnier-quentin** [comment]
Have you tested it ?

**Comment by Dodofox** [comment]
No, i'm not. Last time i didn't had time but i will try it Wednesday or Thursday. Sorry about late.


________________________________
De : qgarnier <notifications@github.com>
Envoyé : lundi 14 novembre 2016 15:20
À : centreon/centreon-plugins
Cc : Dodofox; Author
Objet : Re: [centreon/centreon-plugins] Improve tha databassize calculation (#518)


Have you tested it ?

-

**Comment by Dodofox** [comment]
Hi,

After trying this, it's not working on centreon for sql server here (SQL 2008, 2012, 2014). Your script seems to be based on objects that no longer exist since sql2000 (for example master..sysusages). 

Sorry about that. I think my proposal will work :). What do you think  ?

**Comment by garnier-quentin** [comment]
Thnaks i will try it

**Comment by Dodofox** [comment]
Hi quentin, 
Have you tried it ?

**Comment by garnier-quentin** [comment]
I don't forget. I test it next week

**Comment by garnier-quentin** [comment]
I have done some tests and i have crazy value for 'msdb', 'master', 'tempdb' database size.

**Comment by Dodofox** [comment]
What are you calling "crazy value" ?

**Comment by garnier-quentin** [comment]
Should be interesting to use that requests. But it don't get it to have good used_size. To add 'dbf.size' value and multiply by '* 8 * 1024'. I get the good size value in Bytes.
```
SELECT
          $database_name,,
          ISNULL(fg.name, 'TLOGS'),
          dbf.name,
          dbf.is_media_read_only,
          dbf.is_read_only,
          dbf.is_sparse, -- erstmal wurscht, evt. sys.dm_io_virtual_file_stats fragen
          -- dbf.size * 8.0 * 1024,
          -- dbf.max_size * 8.0 * 1024 AS max_size,
          -- dbf.growth,
          -- FILEPROPERTY(dbf.NAME,'SpaceUsed') * 8.0 * 1024 AS used_size,
          dbf.size,
          dbf.max_size,
          dbf.growth,
          dbf.is_percent_growth,
          FILEPROPERTY(dbf.NAME,'SpaceUsed') AS used_size,
          dbf.type_desc,
          dbf.state_desc,
          UPPER(SUBSTRING(dbf.physical_name, 1, 1)) AS filesystem_drive_letter,
          dbf.physical_name AS filesystem_path
        FROM
          sys.database_files AS dbf --use sys.master_files if the database is read only (more recent data)
        LEFT OUTER JOIN
          -- leider muss man mit AS arbeiten statt database_files.data_space_id.
          -- das kracht bei 2005-compatibility-dbs wegen irgendeines ansi-92/outer-join syntaxmischmaschs
          sys.filegroups AS fg
        ON
          dbf.data_space_id = fg.data_space_id
        WHERE
          dbf.type_desc != 'FILESTREAM'
```

**Comment by Sims24** [comment]
@Dodofox Did you give a change to Quentin's proposition ? 

Please let us know otherwise we'll close this PR in a near futur

**Comment by Sims24** [comment]
Timeout

**Pull request closed without merging**
