### PR TITLE
Add plugin OVH API

### PR DESCRIPTION
**Pull request by rk4an**
Known issues:

- Relative path to the OVH API can trigger error (use lib 'cloud/ovh')
- The plugin ask for a "--hostname" parameter which can be deleted
- Need to check some failure case
- Need to double check OVH licence for the lib

### CODE REVIEW

**Comment by garnier-quentin** [comment]
Thanks for the PR. COuld you use the centreon-plugins http lib ? And use a custom mode to manage the OVH API ?

**Comment by rk4an** [comment]
Hi,

I'm not very familiar with Perl, can you explain me how to do that please?

**Comment by garnier-quentin** [comment]
I have done the SMS mode. Could you test it and see if it's working ?

**Comment by garnier-quentin** [comment]
Could you test it ?

**Comment by rk4an** [comment]
Hi,

Sorry but I have a 403 forbidden when I trying this plugin

**Comment by rk4an** [comment]
Ok it's working sorry, my credential was limited to only one sms service so I create another one with full permission. Thanks

**Comment by rk4an** [comment]
There are just a mistake on the critical-left I think:

--critical-left=40
CRITICAL: Service 'sms-vexxx' SMS left : 89 | 'left'=89sms;;0:40;0;

**Comment by garnier-quentin** [comment]
It's like that: --critical-left=40:

**Comment by rk4an** [comment]
Ok thanks it works

**Comment by garnier-quentin** [comment]
Sorry for the delay. Could you test the 'quota-usage' mode ?

**Pull request closed without merging**
