### PR TITLE
cloud::microsoft::office365::azuread - add Directory Size usage check (AD Quota)

### PR DESCRIPTION
**Pull request by matoy**
## Description

**PLEASE MAKE SURE THAT THE BRANCH PR INCLUDES JIRA TICKET ID** (_for centreon-internal_)

Please include a short resume of the changes and what is the purpose of PR. Any relevant information should be added to help:
* **QA Team** (Quality Assurance) with tests.
* **reviewers** to understand what are the stakes of the pull request.

**Fixes** # (issue)

## Type of change

- [ ] Patch fixing an issue (non-breaking change)
- [X] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software

## Target serie

- [X] 21.04.x
- [X] 21.10.x
- [X] 22.04.x
- [X] 22.10.x (master)

<h2> How this pull request can be tested ? </h2>

New plugin to check Azure AD stuff.
1 mode in included for now but some others may follow in the future

/usr/lib/centreon/plugins//centreon-plugins/centreon_plugins.pl --plugin=cloud::microsoft::office365::azuread::plugin --custommode='graphapi' --mode='directory-size-usage' --tenant='xxx' --client-id='xxx' --client-secret='xxx'
WARNING: Directory size usage : 264943/309000 (85.74%) | 'directorysizeusage'=264943;0:247200;0:278100;0;309000

#### Community contributors & Centreon team

- [X] I have followed the **coding style guidelines** provided by Centreon
- [X] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [X] I have commented my code, especially **hard-to-understand areas** of the PR.
- [X] I have **rebased** my development branch on the base branch (master, maintenance).

### CODE REVIEW

**Comment by Sims24** [comment]
Hi @matoy ! 

Thanks that looks great! 

Any pointer to the doc of /beta/organization endpoint? Couldn't find it. 

Just found this which is interesting https://techcommunity.microsoft.com/t5/core-infrastructure-and-security/the-case-of-azure-ad-quota-exhaustion/ba-p/2496133 but I would like to know if we can add more things like the kind of object contributing to the overall quota. 

Thanks

**Comment by matoy** [comment]
yes, sure.

graph api beta:
https://docs.microsoft.com/en-us/graph/api/overview?view=graph-rest-beta

org details:
https://docs.microsoft.com/en-us/graph/api/organization-get?view=graph-rest-beta&tabs=http

directory size usage/quota looks to be the most interesting.

**Comment by Sims24** [comment]
Thanks, yeah unfortunately there's nothing very interesting except quota. Thanks!

**Comment by Sims24** [comment]
@matoy I made some fix on label, indent, and apply some guidelines (force_new_perfdata). 

Could you test it and tell me if everything's OK? 

Thanks

**Comment by matoy** [comment]
just fixed something you reworked.
tested and ok now.

OK: Directory size usage : 265079/309000 (85.79%) | 'azure.ad.directory.usage.count'=265079;0:278100;0:293550;0;309000

**Comment by Sims24** [comment]
Thanks!

**Review by Sims24 — APPROVED** [review]

**Comment by Sims24** [comment]
Just wondering, did you have to grant any other rights to the user ? 

We usually assign these, but it seems not enough for some people, any idea?

image

**Comment by matoy** [comment]
Hi,

I have only these 4 permissions, i guess only directory.read.all should be necessary.
(application, not delegated)

image

**Pull request merged**
