### PR TITLE
Add time mode to Mikrotik

### PR DESCRIPTION
**Pull request by CPbN**
Hi,

This mode simply adds time mode to `network::mikrotik::snmp::plugin`.

Thank you :+1:

### CODE REVIEW

**Comment by garnier-quentin** [comment]
I dont understand why you want to add ntp mode ?

**Comment by CPbN** [comment]
So that we can verify that device date/time is correctly set (and is not drifting), comparing to the engine localtime (or to NTP server if provided using `--ntp-hostname`).
I discovered many routers not synced in time, which has some drawbacks such as difficult troubleshooting / log reading, schedule tasks not in time etc...
Monitoring time sync then makes sense :)

**Comment by CPbN** [comment]
Perhaps the `snmp_standard::mode::ntp` should have been better named `snmp_standard::mode::time`, as NTP is just an option to this mode.

**Comment by garnier-quentin** [comment]
Ok i see.

**Comment by CPbN** [comment]
Thank you Quentin :)

**Pull request merged**
