### PR TITLE
enh(checkpoint) add some standard modes

### PR DESCRIPTION
**Pull request by UrBnW**
Hi,

Let's add some standard modes to Checkpoint plugin.

Thx 👍

### CODE REVIEW

**Comment by garnier-quentin** [comment]
For storage, maybe i prefer to use checkpoint mib. Could you provide snmpwalk for:
.1.3.6.1.4.1.2620.1.6.7.3
.1.3.6.1.4.1.2620.1.6.7.6

**Comment by UrBnW** [comment]
```
.1.3.6.1.4.1.2620.1.6.7.3.3.0 = Gauge32: 76
.1.3.6.1.4.1.2620.1.6.7.3.4.0 = Counter64: 26342584320
.1.3.6.1.4.1.2620.1.6.7.3.5.0 = Counter64: 26342584320
.1.3.6.1.4.1.2620.1.6.7.3.6.0 = Counter64: 34342961152
.1.3.6.1.4.1.2620.1.6.7.3.7.0 = STRING: "FWDIR"

.1.3.6.1.4.1.2620.1.6.7.6.1.1.1.0 = Gauge32: 1
.1.3.6.1.4.1.2620.1.6.7.6.1.1.2.0 = Gauge32: 2
.1.3.6.1.4.1.2620.1.6.7.6.1.1.3.0 = Gauge32: 3
.1.3.6.1.4.1.2620.1.6.7.6.1.2.1.0 = STRING: "/"
.1.3.6.1.4.1.2620.1.6.7.6.1.2.2.0 = STRING: "/boot"
.1.3.6.1.4.1.2620.1.6.7.6.1.2.3.0 = STRING: "/var/log"
.1.3.6.1.4.1.2620.1.6.7.6.1.3.1.0 = Counter64: 34342961152
.1.3.6.1.4.1.2620.1.6.7.6.1.3.2.0 = Counter64: 304559104
.1.3.6.1.4.1.2620.1.6.7.6.1.3.3.0 = Counter64: 160982630400
.1.3.6.1.4.1.2620.1.6.7.6.1.4.1.0 = Counter64: 8000376832
.1.3.6.1.4.1.2620.1.6.7.6.1.4.2.0 = Counter64: 61826048
.1.3.6.1.4.1.2620.1.6.7.6.1.4.3.0 = Counter64: 1985806336
.1.3.6.1.4.1.2620.1.6.7.6.1.5.1.0 = Counter64: 26342584320
.1.3.6.1.4.1.2620.1.6.7.6.1.5.2.0 = Counter64: 242733056
.1.3.6.1.4.1.2620.1.6.7.6.1.5.3.0 = Counter64: 158996824064
.1.3.6.1.4.1.2620.1.6.7.6.1.6.1.0 = Gauge32: 76
.1.3.6.1.4.1.2620.1.6.7.6.1.6.2.0 = Gauge32: 79
.1.3.6.1.4.1.2620.1.6.7.6.1.6.3.0 = Gauge32: 98
.1.3.6.1.4.1.2620.1.6.7.6.1.7.1.0 = Counter64: 26342584320
.1.3.6.1.4.1.2620.1.6.7.6.1.7.2.0 = Counter64: 227008512
.1.3.6.1.4.1.2620.1.6.7.6.1.7.3.0 = Counter64: 158996824064
.1.3.6.1.4.1.2620.1.6.7.6.1.8.1.0 = Gauge32: 76
.1.3.6.1.4.1.2620.1.6.7.6.1.8.2.0 = Gauge32: 74
.1.3.6.1.4.1.2620.1.6.7.6.1.8.3.0 = Gauge32: 98
```
Sounds like `.1.3.6.1.4.1.2620.1.6.7.3` is not really useful, seems to return the `.1.3.6.1.4.1.2620.1.6.7.6` numbers for `/`.
Note that I get the same `.1.3.6.1.4.1.2620.1.6.7.6` results with `storage` mode.

**Comment by garnier-quentin** [comment]
storage standard mode have issue with big disks also. Maybe it's better to use checkpoint table.

**Comment by garnier-quentin** [comment]
I could close that issue: https://github.com/centreon/centreon-plugins/issues/1634

**Comment by UrBnW** [comment]
I'm rather surprised to find big/hug disks in Checkpoint devices :)
Anyway, if it can solve an issue, why not yes of course 👍

**Comment by UrBnW** [comment]
While here, if I may, would be nice to implement multi-core CPU counters, as in `snmp_standard::mode::cpu`.
I use `snmp_standard::mode::cpu` with Checkpoint devices, which runs fine, but here are the dedicated Checkpoint counters :

```
.1.3.6.1.4.1.2620.1.6.7.5.1.1.1.0 = Gauge32: 1
.1.3.6.1.4.1.2620.1.6.7.5.1.1.2.0 = Gauge32: 2
.1.3.6.1.4.1.2620.1.6.7.5.1.1.3.0 = Gauge32: 3
.1.3.6.1.4.1.2620.1.6.7.5.1.1.4.0 = Gauge32: 4
.1.3.6.1.4.1.2620.1.6.7.5.1.1.5.0 = Gauge32: 5
.1.3.6.1.4.1.2620.1.6.7.5.1.1.6.0 = Gauge32: 6
.1.3.6.1.4.1.2620.1.6.7.5.1.1.7.0 = Gauge32: 7
.1.3.6.1.4.1.2620.1.6.7.5.1.1.8.0 = Gauge32: 8
.1.3.6.1.4.1.2620.1.6.7.5.1.1.9.0 = Gauge32: 9
.1.3.6.1.4.1.2620.1.6.7.5.1.1.10.0 = Gauge32: 10
.1.3.6.1.4.1.2620.1.6.7.5.1.1.11.0 = Gauge32: 11
.1.3.6.1.4.1.2620.1.6.7.5.1.1.12.0 = Gauge32: 12
.1.3.6.1.4.1.2620.1.6.7.5.1.1.13.0 = Gauge32: 13
.1.3.6.1.4.1.2620.1.6.7.5.1.1.14.0 = Gauge32: 14
.1.3.6.1.4.1.2620.1.6.7.5.1.1.15.0 = Gauge32: 15
.1.3.6.1.4.1.2620.1.6.7.5.1.1.16.0 = Gauge32: 16
.1.3.6.1.4.1.2620.1.6.7.5.1.1.17.0 = Gauge32: 17
.1.3.6.1.4.1.2620.1.6.7.5.1.1.18.0 = Gauge32: 18
.1.3.6.1.4.1.2620.1.6.7.5.1.1.19.0 = Gauge32: 19
.1.3.6.1.4.1.2620.1.6.7.5.1.1.20.0 = Gauge32: 20
.1.3.6.1.4.1.2620.1.6.7.5.1.1.21.0 = Gauge32: 21
.1.3.6.1.4.1.2620.1.6.7.5.1.1.22.0 = Gauge32: 22
.1.3.6.1.4.1.2620.1.6.7.5.1.1.23.0 = Gauge32: 23
.1.3.6.1.4.1.2620.1.6.7.5.1.1.24.0 = Gauge32: 24
.1.3.6.1.4.1.2620.1.6.7.5.1.1.25.0 = Gauge32: 25
.1.3.6.1.4.1.2620.1.6.7.5.1.1.26.0 = Gauge32: 26
.1.3.6.1.4.1.2620.1.6.7.5.1.1.27.0 = Gauge32: 27
.1.3.6.1.4.1.2620.1.6.7.5.1.1.28.0 = Gauge32: 28
.1.3.6.1.4.1.2620.1.6.7.5.1.1.29.0 = Gauge32: 29
.1.3.6.1.4.1.2620.1.6.7.5.1.1.30.0 = Gauge32: 30
.1.3.6.1.4.1.2620.1.6.7.5.1.1.31.0 = Gauge32: 31
.1.3.6.1.4.1.2620.1.6.7.5.1.1.32.0 = Gauge32: 32
.1.3.6.1.4.1.2620.1.6.7.5.1.1.33.0 = Gauge32: 33
.1.3.6.1.4.1.2620.1.6.7.5.1.1.34.0 = Gauge32: 34
.1.3.6.1.4.1.2620.1.6.7.5.1.1.35.0 = Gauge32: 35
.1.3.6.1.4.1.2620.1.6.7.5.1.1.36.0 = Gauge32: 36
.1.3.6.1.4.1.2620.1.6.7.5.1.1.37.0 = Gauge32: 37
.1.3.6.1.4.1.2620.1.6.7.5.1.1.38.0 = Gauge32: 38
.1.3.6.1.4.1.2620.1.6.7.5.1.1.39.0 = Gauge32: 39
.1.3.6.1.4.1.2620.1.6.7.5.1.1.40.0 = Gauge32: 40
.1.3.6.1.4.1.2620.1.6.7.5.1.1.41.0 = Gauge32: 41
.1.3.6.1.4.1.2620.1.6.7.5.1.1.42.0 = Gauge32: 42
.1.3.6.1.4.1.2620.1.6.7.5.1.1.43.0 = Gauge32: 43
.1.3.6.1.4.1.2620.1.6.7.5.1.1.44.0 = Gauge32: 44
.1.3.6.1.4.1.2620.1.6.7.5.1.1.45.0 = Gauge32: 45
.1.3.6.1.4.1.2620.1.6.7.5.1.1.46.0 = Gauge32: 46
.1.3.6.1.4.1.2620.1.6.7.5.1.1.47.0 = Gauge32: 47
.1.3.6.1.4.1.2620.1.6.7.5.1.1.48.0 = Gauge32: 48
.1.3.6.1.4.1.2620.1.6.7.5.1.2.1.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.2.2.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.2.3.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.2.4.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.2.5.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.2.6.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.2.7.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.2.8.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.2.9.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.2.10.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.2.11.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.2.12.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.2.13.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.2.14.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.2.15.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.2.16.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.2.17.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.2.18.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.2.19.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.2.20.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.2.21.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.2.22.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.2.23.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.2.24.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.2.25.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.2.26.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.2.27.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.2.28.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.2.29.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.2.30.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.2.31.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.2.32.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.2.33.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.2.34.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.2.35.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.2.36.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.2.37.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.2.38.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.2.39.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.2.40.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.2.41.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.2.42.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.2.43.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.2.44.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.2.45.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.2.46.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.2.47.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.2.48.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.3.1.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.3.2.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.3.3.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.3.4.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.3.5.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.3.6.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.3.7.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.3.8.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.3.9.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.3.10.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.3.11.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.3.12.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.3.13.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.3.14.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.3.15.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.3.16.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.3.17.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.3.18.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.3.19.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.3.20.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.3.21.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.3.22.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.3.23.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.3.24.0 = Gauge32: 1
.1.3.6.1.4.1.2620.1.6.7.5.1.3.25.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.3.26.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.3.27.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.3.28.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.3.29.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.3.30.0 = Gauge32: 1
.1.3.6.1.4.1.2620.1.6.7.5.1.3.31.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.3.32.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.3.33.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.3.34.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.3.35.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.3.36.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.3.37.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.3.38.0 = Gauge32: 1
.1.3.6.1.4.1.2620.1.6.7.5.1.3.39.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.3.40.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.3.41.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.3.42.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.3.43.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.3.44.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.3.45.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.3.46.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.3.47.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.3.48.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.4.1.0 = Gauge32: 100
.1.3.6.1.4.1.2620.1.6.7.5.1.4.2.0 = Gauge32: 100
.1.3.6.1.4.1.2620.1.6.7.5.1.4.3.0 = Gauge32: 100
.1.3.6.1.4.1.2620.1.6.7.5.1.4.4.0 = Gauge32: 100
.1.3.6.1.4.1.2620.1.6.7.5.1.4.5.0 = Gauge32: 100
.1.3.6.1.4.1.2620.1.6.7.5.1.4.6.0 = Gauge32: 100
.1.3.6.1.4.1.2620.1.6.7.5.1.4.7.0 = Gauge32: 100
.1.3.6.1.4.1.2620.1.6.7.5.1.4.8.0 = Gauge32: 100
.1.3.6.1.4.1.2620.1.6.7.5.1.4.9.0 = Gauge32: 100
.1.3.6.1.4.1.2620.1.6.7.5.1.4.10.0 = Gauge32: 100
.1.3.6.1.4.1.2620.1.6.7.5.1.4.11.0 = Gauge32: 100
.1.3.6.1.4.1.2620.1.6.7.5.1.4.12.0 = Gauge32: 100
.1.3.6.1.4.1.2620.1.6.7.5.1.4.13.0 = Gauge32: 100
.1.3.6.1.4.1.2620.1.6.7.5.1.4.14.0 = Gauge32: 100
.1.3.6.1.4.1.2620.1.6.7.5.1.4.15.0 = Gauge32: 100
.1.3.6.1.4.1.2620.1.6.7.5.1.4.16.0 = Gauge32: 100
.1.3.6.1.4.1.2620.1.6.7.5.1.4.17.0 = Gauge32: 100
.1.3.6.1.4.1.2620.1.6.7.5.1.4.18.0 = Gauge32: 100
.1.3.6.1.4.1.2620.1.6.7.5.1.4.19.0 = Gauge32: 100
.1.3.6.1.4.1.2620.1.6.7.5.1.4.20.0 = Gauge32: 100
.1.3.6.1.4.1.2620.1.6.7.5.1.4.21.0 = Gauge32: 100
.1.3.6.1.4.1.2620.1.6.7.5.1.4.22.0 = Gauge32: 100
.1.3.6.1.4.1.2620.1.6.7.5.1.4.23.0 = Gauge32: 100
.1.3.6.1.4.1.2620.1.6.7.5.1.4.24.0 = Gauge32: 99
.1.3.6.1.4.1.2620.1.6.7.5.1.4.25.0 = Gauge32: 100
.1.3.6.1.4.1.2620.1.6.7.5.1.4.26.0 = Gauge32: 100
.1.3.6.1.4.1.2620.1.6.7.5.1.4.27.0 = Gauge32: 100
.1.3.6.1.4.1.2620.1.6.7.5.1.4.28.0 = Gauge32: 100
.1.3.6.1.4.1.2620.1.6.7.5.1.4.29.0 = Gauge32: 100
.1.3.6.1.4.1.2620.1.6.7.5.1.4.30.0 = Gauge32: 99
.1.3.6.1.4.1.2620.1.6.7.5.1.4.31.0 = Gauge32: 100
.1.3.6.1.4.1.2620.1.6.7.5.1.4.32.0 = Gauge32: 99
.1.3.6.1.4.1.2620.1.6.7.5.1.4.33.0 = Gauge32: 100
.1.3.6.1.4.1.2620.1.6.7.5.1.4.34.0 = Gauge32: 100
.1.3.6.1.4.1.2620.1.6.7.5.1.4.35.0 = Gauge32: 100
.1.3.6.1.4.1.2620.1.6.7.5.1.4.36.0 = Gauge32: 100
.1.3.6.1.4.1.2620.1.6.7.5.1.4.37.0 = Gauge32: 100
.1.3.6.1.4.1.2620.1.6.7.5.1.4.38.0 = Gauge32: 99
.1.3.6.1.4.1.2620.1.6.7.5.1.4.39.0 = Gauge32: 99
.1.3.6.1.4.1.2620.1.6.7.5.1.4.40.0 = Gauge32: 100
.1.3.6.1.4.1.2620.1.6.7.5.1.4.41.0 = Gauge32: 100
.1.3.6.1.4.1.2620.1.6.7.5.1.4.42.0 = Gauge32: 100
.1.3.6.1.4.1.2620.1.6.7.5.1.4.43.0 = Gauge32: 100
.1.3.6.1.4.1.2620.1.6.7.5.1.4.44.0 = Gauge32: 100
.1.3.6.1.4.1.2620.1.6.7.5.1.4.45.0 = Gauge32: 100
.1.3.6.1.4.1.2620.1.6.7.5.1.4.46.0 = Gauge32: 100
.1.3.6.1.4.1.2620.1.6.7.5.1.4.47.0 = Gauge32: 100
.1.3.6.1.4.1.2620.1.6.7.5.1.4.48.0 = Gauge32: 100
.1.3.6.1.4.1.2620.1.6.7.5.1.5.1.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.5.2.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.5.3.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.5.4.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.5.5.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.5.6.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.5.7.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.5.8.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.5.9.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.5.10.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.5.11.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.5.12.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.5.13.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.5.14.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.5.15.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.5.16.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.5.17.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.5.18.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.5.19.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.5.20.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.5.21.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.5.22.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.5.23.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.5.24.0 = Gauge32: 1
.1.3.6.1.4.1.2620.1.6.7.5.1.5.25.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.5.26.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.5.27.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.5.28.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.5.29.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.5.30.0 = Gauge32: 1
.1.3.6.1.4.1.2620.1.6.7.5.1.5.31.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.5.32.0 = Gauge32: 1
.1.3.6.1.4.1.2620.1.6.7.5.1.5.33.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.5.34.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.5.35.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.5.36.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.5.37.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.5.38.0 = Gauge32: 1
.1.3.6.1.4.1.2620.1.6.7.5.1.5.39.0 = Gauge32: 1
.1.3.6.1.4.1.2620.1.6.7.5.1.5.40.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.5.41.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.5.42.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.5.43.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.5.44.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.5.45.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.5.46.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.5.47.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.5.48.0 = Gauge32: 0
.1.3.6.1.4.1.2620.1.6.7.5.1.7.1.0 = Gauge32: 17610
.1.3.6.1.4.1.2620.1.6.7.5.1.7.2.0 = Gauge32: 17610
.1.3.6.1.4.1.2620.1.6.7.5.1.7.3.0 = Gauge32: 17134
.1.3.6.1.4.1.2620.1.6.7.5.1.7.4.0 = Gauge32: 17610
.1.3.6.1.4.1.2620.1.6.7.5.1.7.5.0 = Gauge32: 17611
.1.3.6.1.4.1.2620.1.6.7.5.1.7.6.0 = Gauge32: 17135
.1.3.6.1.4.1.2620.1.6.7.5.1.7.7.0 = Gauge32: 17611
.1.3.6.1.4.1.2620.1.6.7.5.1.7.8.0 = Gauge32: 17611
.1.3.6.1.4.1.2620.1.6.7.5.1.7.9.0 = Gauge32: 17611
.1.3.6.1.4.1.2620.1.6.7.5.1.7.10.0 = Gauge32: 17611
.1.3.6.1.4.1.2620.1.6.7.5.1.7.11.0 = Gauge32: 17611
.1.3.6.1.4.1.2620.1.6.7.5.1.7.12.0 = Gauge32: 17611
.1.3.6.1.4.1.2620.1.6.7.5.1.7.13.0 = Gauge32: 17611
.1.3.6.1.4.1.2620.1.6.7.5.1.7.14.0 = Gauge32: 17611
.1.3.6.1.4.1.2620.1.6.7.5.1.7.15.0 = Gauge32: 17611
.1.3.6.1.4.1.2620.1.6.7.5.1.7.16.0 = Gauge32: 17611
.1.3.6.1.4.1.2620.1.6.7.5.1.7.17.0 = Gauge32: 17611
.1.3.6.1.4.1.2620.1.6.7.5.1.7.18.0 = Gauge32: 17611
.1.3.6.1.4.1.2620.1.6.7.5.1.7.19.0 = Gauge32: 17611
.1.3.6.1.4.1.2620.1.6.7.5.1.7.20.0 = Gauge32: 17136
.1.3.6.1.4.1.2620.1.6.7.5.1.7.21.0 = Gauge32: 17612
.1.3.6.1.4.1.2620.1.6.7.5.1.7.22.0 = Gauge32: 17612
.1.3.6.1.4.1.2620.1.6.7.5.1.7.23.0 = Gauge32: 17612
.1.3.6.1.4.1.2620.1.6.7.5.1.7.24.0 = Gauge32: 17612
.1.3.6.1.4.1.2620.1.6.7.5.1.7.25.0 = Gauge32: 17136
.1.3.6.1.4.1.2620.1.6.7.5.1.7.26.0 = Gauge32: 17612
.1.3.6.1.4.1.2620.1.6.7.5.1.7.27.0 = Gauge32: 17136
.1.3.6.1.4.1.2620.1.6.7.5.1.7.28.0 = Gauge32: 17136
.1.3.6.1.4.1.2620.1.6.7.5.1.7.29.0 = Gauge32: 17136
.1.3.6.1.4.1.2620.1.6.7.5.1.7.30.0 = Gauge32: 17612
.1.3.6.1.4.1.2620.1.6.7.5.1.7.31.0 = Gauge32: 17612
.1.3.6.1.4.1.2620.1.6.7.5.1.7.32.0 = Gauge32: 17612
.1.3.6.1.4.1.2620.1.6.7.5.1.7.33.0 = Gauge32: 17612
.1.3.6.1.4.1.2620.1.6.7.5.1.7.34.0 = Gauge32: 17612
.1.3.6.1.4.1.2620.1.6.7.5.1.7.35.0 = Gauge32: 17612
.1.3.6.1.4.1.2620.1.6.7.5.1.7.36.0 = Gauge32: 17612
.1.3.6.1.4.1.2620.1.6.7.5.1.7.37.0 = Gauge32: 17136
.1.3.6.1.4.1.2620.1.6.7.5.1.7.38.0 = Gauge32: 17612
.1.3.6.1.4.1.2620.1.6.7.5.1.7.39.0 = Gauge32: 17612
.1.3.6.1.4.1.2620.1.6.7.5.1.7.40.0 = Gauge32: 17612
.1.3.6.1.4.1.2620.1.6.7.5.1.7.41.0 = Gauge32: 17612
.1.3.6.1.4.1.2620.1.6.7.5.1.7.42.0 = Gauge32: 17612
.1.3.6.1.4.1.2620.1.6.7.5.1.7.43.0 = Gauge32: 17613
.1.3.6.1.4.1.2620.1.6.7.5.1.7.44.0 = Gauge32: 17613
.1.3.6.1.4.1.2620.1.6.7.5.1.7.45.0 = Gauge32: 17613
.1.3.6.1.4.1.2620.1.6.7.5.1.7.46.0 = Gauge32: 17613
.1.3.6.1.4.1.2620.1.6.7.5.1.7.47.0 = Gauge32: 17613
.1.3.6.1.4.1.2620.1.6.7.5.1.7.48.0 = Gauge32: 17137
```

Many thx 👍

**Comment by UrBnW** [comment]
Well I can do it myself, cloning `snmp_standard::mode::cpu` and browsing `.1.3.6.1.4.1.2620.1.6.7.5.1.5`...

**Pull request merged**
