### PR TITLE
enh(watchguard) add some global counters

### PR DESCRIPTION
**Pull request by UrBnW**
Hi,

Let's add some Watchguard VPN global counters.

Thx 👍

### CODE REVIEW

**Comment by garnier-quentin** [comment]
Could you test it ?

**Comment by UrBnW** [comment]
It works, but I just faced a bug where an instance (tunnel) value is sometimes greater than the total...
I suspect the tunnels table not to have consistent IDs, which would then lead to this bug.
I'm troubleshooting to be sure.

**Comment by garnier-quentin** [comment]
I see the issue. yes we cannot increment like that. i remove

**Comment by UrBnW** [comment]
OK with last fixes, thx 👍

**Pull request closed without merging**
