### PR TITLE
New 3CX plugin

### PR DESCRIPTION
**Pull request by CPbN**
Hi,

Here is a plugin to monitor 3CX PBX status.

Thank you :+1:

### CODE REVIEW

**Comment by garnier-quentin** [comment]
You could put it in apps/voip

**Comment by CPbN** [comment]
Done @garnier-quentin !
I also added some perfdata.
Plugin's ready to be reviewed :+1:

**Comment by CPbN** [comment]
Many thanks Quentin :+1:

**Comment by garnier-quentin** [comment]
Could you provide me the result of following request:
/api/SystemStatus/GetSingleStatus
/api/SystemStatus

**Comment by garnier-quentin** [comment]
I don't understand that:
```
$self->{output}->output_add(severity => $self->{single}->{$item} ? 'OK' : 'CRITICAL',
                                    short_msg => $item);
``
It will be always OK.

**Comment by CPbN** [comment]
Just sent by mail :)

**Pull request merged**
