### PR TITLE
Mikrotik, update mode

### PR DESCRIPTION
**Pull request by CPbN**
Hi,

Here's a new mode to Mikrotik plugin to check for RouterOS updates.

Mode can get latest available version by itself.
One can also provide his expected version, for example if he wants his routers to all run a specific version.

Thank you 👍

### CODE REVIEW

**Comment by garnier-quentin** [comment]
Sorry but for me it's not monitoring directly (more configuration). You can use your mode with dyn-mode option.

**Comment by CPbN** [comment]
Yes it's between monitoring and device configuration...
One may like to have version check in Centreon to be sure all his devices (dozens, hundreds... of devices) are running the expected / last software version. At least I encountered this situation :)
I like to have everything in Centreon Plugins directly :)
But as you mentioned perhaps it's not the best place...

**Comment by CPbN** [comment]
As there are some modes to check for OS pending updates, I wondered :)

**Comment by garnier-quentin** [comment]
You can use centreon-plugins. dyn-mode option is for that.
For OS, it's more "useful"

**Pull request closed without merging**
