### PR TITLE
Take into account "data and log" segments to avoid negative values for log usage

### PR DESCRIPTION
**Pull request by sebastien-prudhomme**
See http://infocenter.sybase.com/help/index.jsp?topic=/com.sybase.infocenter.dc31644.1550/html/sag2/sag2175.htm

### CODE REVIEW

**Comment by garnier-quentin** [comment]
I don't really understand. If you add data with logs it's no more logs. How log value can be negative ?

**Comment by sebastien-prudhomme** [comment]
Negative values without the patch:

```
/usr/lib/nagios/plugins/centreon_plugins.pl --plugin database::sybase::plugin --mode databases-size --hostname 1.2.3.4 --port 1234 --username centreon --password centreon --warning-data 95 --warning-log 95 --critical-data 99 --critical-log 99 --range-perfdata 1
CRITICAL: Database 'sybsystemdb' Total Log: 3.00 MB Used: -3287040.00 B (-104.49%) Free: 6.13 MB (204.49%) | 'data_used_rsbdnu1_ar_rssd'=1073569792B;1530082099;1594506608;0;1610612736 'log_used_rsbdnu1_ar_rssd'=2099200B;510027366;531502202;0;536870912 'data_used_master'=70223872B;448266240;467140608;0;471859200 'data_used_model'=1773568B;2988441;3114270;0;3145728 'data_used_sybsystemdb'=20480B;4980736;5190451;0;5242880 'log_used_sybsystemdb'=-3287040B;2988441;3114270;0;3145728 'data_used_sybsystemprocs'=129980416B;498073600;519045120;0;524288000 'data_used_tempdb'=5986304B;1024039321;1067156766;0;1077936128 'data_used_tempdb_sa'=2285568B;127506841;132875550;0;134217728
```

The SQL result without the patch:

```
 db_name                        data_size                                     data_used                      log_size                                      log_used                                       
 ------------------------------ --------------------------------------------- ------------------------------ --------------------------------------------- ---------------------------------------------- 
 RSBDNU1_AR_RSSD                                                   1610612736                     1073569792                                     536870912                                        2099200 
 master                                                             471859200                       70223872                                          NULL                                           NULL 
 model                                                                3145728                        1773568                                          NULL                                           NULL 
 sybsystemdb                                                          5242880                          20480                                       3145728                                       -3287040 
 sybsystemprocs                                                     524288000                      129980416                                          NULL                                           NULL 
 tempdb                                                            1077936128                        5986304                                          NULL                                           NULL 
 tempdb_sa                                                          134217728                        2285568                                          NULL                                           NULL 

(7 rows affected)
```

sybsystemdb is using a "data+log" segment (segmap = 7) and a "log only" segment (segmap = 4). The "data+log" segment size is not taken into account when computing the log total size into the original SQL request. But as "logsegment_freepages" take all segments into account, you have a negative value.

**Comment by sebastien-prudhomme** [comment]
Other references:
* https://benohead.com/sybase-size-of-data-and-log-segments-for-all-databases/
* http://alexhanin.blogspot.fr/2010/12/data-and-log-space-usage-in-sybase.html

**Comment by garnier-quentin** [comment]
Thanks for the explain.

**Pull request merged**
