### PR TITLE
enh(watchguard) Add standard modes

### PR DESCRIPTION
**Pull request by UrBnW**
Hi,
Let's add some standard modes to Watchguard.
Thx 👍

### CODE REVIEW

**Comment by UrBnW** [comment]
I just added `memory` and `swap` modes, which are fully supported :
https://www.watchguard.com/help/docs/help-center/en-US/Content/en-US/Fireware/basicadmin/snmp_about_mibs_c.html
_Fireware also supports some statistics from the **UCD-SNMP-MIB** third-party MIB. For more information, see the knowledge base article [About Third-Party SNMP MIBs](https://watchguardsupport.secure.force.com/publicKB/?type=KBArticle&SFDCID=kA22A000000HQ0PSAW&lang=en_US)._
`snmp_standard::mode::cpudetailed` is also supported as per the above link, I tested it, it works.

`snmp_standard::mode::cpu` also works (even if its OIDs are not from **`UCD-SNMP-MIB`**).
I would be glad to replace current `cpu` mode with this `snmp_standard::mode::cpu` one, as it gives much better results, as we can work per-core to better monitor the device :

Current Watchguard `cpu` mode :
```
OK: CPU 1 minute : 1.00 %, 5 minutes : 2.00 %, 15 minutes : 1.00 % | 'cpu_1min'=1.00%;;;0;100 'cpu_5min'=2.00%;;;0;100 'cpu_15min'=1.00%;;;0;100
```

`snmp_standard::mode::cpu` mode :
```
OK: 8 CPU(s) average usage is 3.25 % | 'total_cpu_avg'=3.25%;;;0;100 'cpu_0'=4.00%;;;0;100 'cpu_1'=4.00%;;;0;100 'cpu_2'=3.00%;;;0;100 'cpu_3'=3.00%;;;0;100 'cpu_4'=3.00%;;;0;100 'cpu_5'=3.00%;;;0;100 'cpu_6'=3.00%;;;0;100 'cpu_7'=3.00%;;;0;100
```

``snmp_standard::mode::cpudetailed` mode :
```
OK: CPU Usage: User 0.64 %, Nice 0.00 %, System 2.02 %, Idle 96.56 %, Wait 0.05 %, Kernel 0.00 %, Interrupt 0.00 %, Soft Irq 0.72 %, Steal 0.00 %, Guest 0.00 %, Guest Nice 0.00 % | 'user'=0.64%;;;0;100 'nice'=0.00%;;;0;100 'system'=2.02%;;;0;100 'idle'=96.56%;;;0;100 'wait'=0.05%;;;0;100 'kernel'=0.00%;;;0;100 'interrupt'=0.00%;;;0;100 'softirq'=0.72%;;;0;100 'steal'=0.00%;;;0;100 'guest'=0.00%;;;0;100 'guestnice'=0.00%;;;0;100
```

Any thoughts ?
Thx 👍

**Comment by UrBnW** [comment]
Well, actually, `snmp_standard::mode::cpu` IS supported, as the OID used are from `SNMPv2-SMI`, which is clearly listed in the link above.
So we can safely go with it 👍

**Comment by garnier-quentin** [comment]
I prefer to keep the CPU mode (to avoid to break for old firmware). I added new perfdata otherwise.

**Comment by UrBnW** [comment]
Thank you Quentin.
Are you sure old firmwares do not support `SNMPv2-SMI` ?
Perhaps we could use `snmp_standard::mode::cpu`, and keep the current `cpu` mode as `cpulegacy` ?
Having counters by core is useful, as we can easily detect a 100% stuck core.
Thank you 👍

**Comment by garnier-quentin** [comment]
You can use the snmp standard mode as a dyn mode.

**Comment by UrBnW** [comment]
Is this compliant with the Perl Connector ?
As then the standard mode will not be embedded into the plugin file.

**Comment by garnier-quentin** [comment]
Yes it should. You can add it in your fatpack file also.

**Comment by UrBnW** [comment]
More convenient when it's in the `.rpm` package, but I'll give a try (never used dyn-mode before).

**Comment by UrBnW** [comment]
OK the following works :
`--plugin=network::watchguard::snmp::plugin --dyn-mode=snmp_standard::mode::cpu`
I'm lucky enough `snmp_standard::mode::cpu` is already loaded into the Perl Connector by another plugin, otherwise it would have failed.

**Comment by UrBnW** [comment]
OK the following works :
`--plugin=network::watchguard::snmp::plugin --dyn-mode=snmp_standard::mode::cpu`
I'm lucky enough `snmp_standard::mode::cpu` is already loaded into the Perl Connector by another plugin, otherwise it would have failed.
Not the best solution though, but I can live with this.

**Pull request closed without merging**
