### PR TITLE
Change memory calculation for redhat 7.1

### PR DESCRIPTION
**Pull request by mullergg**
According to : https://access.redhat.com/solutions/406773

I added a function to find what redhat version we have and then adapt the calculation method.

### CODE REVIEW

**Comment by garnier-quentin** [comment]
Why do you want to change it for rhel 7.1 ?

**Comment by garnier-quentin** [comment]
Ok. I'll take a look soon (thursday)

**Comment by mullergg** [comment]
Thanks

**Comment by garnier-quentin** [comment]
Could you test it ?
For me, i think we should use SReclaimable no ?

**Comment by mullergg** [comment]
The check of the red hat version is wrong.
The regex does not match on Redhat because it's Red Hat in the file.
It is also wrong because you don't match on version like 8.0 or every version > 7.1 cotaining a 0 in minor.

Do you also remove the Slab value in the output and perfdata on purpose ?

I also hesitate to do the calculation on SReclaimable value, because the command free is based on this value. But Red Hat seems to say that the real RAM consumption is based on Slab. 
So I don't know which one has the right answer.

**Comment by garnier-quentin** [comment]
Sorry for the delay. i have fixed it.

**Comment by mullergg** [comment]
Ok thanks, I will try to test it soon.

**Comment by mullergg** [comment]
Hello !
It seems to works, tanks for the update.
Did you analyze if we have to use Slab or SReclaimable ?

**Comment by garnier-quentin** [comment]
we are going to use what rhel tell us in the doc.

**Pull request closed without merging**
