### PR TITLE
(plugin) apps::ceph::restapi - add new df mode

### PR DESCRIPTION
**Pull request by ParadoxGuitarist**
## Description

Adding raw usage percentage from the rest API. 

**PLEASE MAKE SURE THAT THE BRANCH PR INCLUDES JIRA TICKET ID** (_for centreon-internal_)

Please include a short resume of the changes and what is the purpose of PR. Any relevant information should be added to help:
* **QA Team** (Quality Assurance) with tests.
* **reviewers** to understand what are the stakes of the pull request.

**Fixes** #4038

## Type of change

- [ ] Patch fixing an issue (non-breaking change)
- [X] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software

## Target series

- [ ] 21.10.x
- [ ] 22.04.x
- [ ] 22.10.x
- [ ] 23.04.x (master)

<h2> How this pull request can be tested ? </h2>

Please describe the **procedure** to verify that the goal of the PR is matched. Provide clear instructions so that it can be **correctly tested**.

You have to have a ceph API instance to test against. Something like 
```
 perl centreon_plugins.pl --plugin=apps::ceph::restapi::plugin --mode=df --hostname='cephhost.localhost' --port='8443' --proto='https' --api-username='centreon' --api-password='supersecretpassword' --insecure --critical-raw-usage-prcnt=80 --warning-raw-usage-prcnt=70

```

#### Community contributors & Centreon team
- [X] I have followed the **coding style guidelines** provided by Centreon
- [X] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [X] I have commented my code, especially **hard-to-understand areas** of the PR.
- [X] I have **rebased** my development branch on the base branch (master, maintenance).

### CODE REVIEW

**Comment by ParadoxGuitarist** [comment]
@Sims24 

It's actually using the same endpoint as the other modes. There's a LOT in that endpoint so I don't know if you have access to the output from the previous PRs but I attached the relevant bits. Let me know if you still need a dump of that payload, just know it's a mess. (expanded it's over 15,000 lines)

**Comment by ParadoxGuitarist** [comment]
@Sims24 Was that example I threw in there alright? It **is** the full output from the `{health}->{df}->{stats}` object.

**Comment by Sims24** [comment]
Hi @ParadoxGuitarist 

Yes it's more than enough, we will just make it more compliant with what we do when we manage space utilization in terms of output, thresholds, etc. 

This way, users will be able to use the bytes or % unit, set threshold on free space left, etc ... 

You can get an idea of how we do that with custom functions here: https://github.com/centreon/centreon-plugins/blob/e40d869bf4a584d1b5228b3b31686ee49a80606a/database/oracle/mode/tablespaceusage.pm. 

We will soon review this and make it ready for an official release. 

Thanks for helping us extend centreon-plugins !

**Comment by ParadoxGuitarist** [comment]
Just checking in to see if you need anything from on on this.

**Comment by kduret** [comment]
replaced by https://github.com/centreon/centreon-plugins/pull/4150

**Pull request closed without merging**
