### PR TITLE
 HTTP expected-content, add expected-(first-)headers options 

### LINKED ISSUE #1099: [apps/protocols/http] Expected headers
Hi,

In `apps::protocols::http::plugin`, when looking for content, for example using `--mode=expected-content`, would be nice to also be able to check for user-provided expected headers.

This at 2 places :
- headers in the very first response, so before redirections ;
- headers in the very last response, so after redirections.

Thus, in only one command, we would be able to do nice things like checking that a host correctly redirects to HTTPS, sets HTTPS headers, and sends the right page :
`--plugin=apps::protocols::http::plugin --mode=expected-content --hostname=my.serv --expected-string="<!--page loaded-->" --expected-header-first="Location: https" --expected-header-last="Strict-Transport-Security:"`

Thank you very much :+1:

### PR DESCRIPTION
**Pull request by CPbN**
Hi,

This closes #1099.
It adds 2 new options to `apps::protocols::http` plugin, mode `expected-content` :
- expected-first-headers
- expected-headers

They allow to match headers, with the first option matching in the very-first received response.

Thank you :+1:

### CODE REVIEW

**Comment by CPbN** [comment]
Conflicts solved.

**Comment by CPbN** [comment]
Some conflicts now due to https://github.com/centreon/centreon-plugins/commit/782fa22f56733d4e29a299834f74b1e5838a8db2.

**Comment by garnier-quentin** [comment]
Yes indeed. You need to manage also the curl backend ;)

**Comment by CPbN** [comment]
Curl `get_first_header` remaining.

**Comment by CPbN** [comment]
I did not found an easy way to do the same with the curl backend.
An idea @garnier-quentin ?
As a last resort, we could disable the `expected-first-header` option without LWP backend...

**Comment by garnier-quentin** [comment]
You need to use that callback (like that we can keep the first header):
https://curl.haxx.se/libcurl/c/CURLOPT_HEADERFUNCTION.html

**Comment by CPbN** [comment]
Note that `Net::Curl::Easy` is not available as a Centos package and thus is not "easy" to install.

**Comment by CPbN** [comment]
OK, PR ready.
Thx :+1:

**Comment by CPbN** [comment]
PR ready, could we think about merging it when you'll have some time @garnier-quentin ?
Many thanks :+1:

**Comment by CPbN** [comment]
Mmmh broken again due to https://github.com/centreon/centreon-plugins/commit/237b2c3904343b27806afe63f28056fdbdf60743 :)

**Comment by garnier-quentin** [comment]
I'm working on it. Don't worry ;)

**Comment by garnier-quentin** [comment]
Done. You can test it!

**Comment by CPbN** [comment]
Nice, thank you very much @garnier-quentin !
I'll test it ASAP and report :+1:

**Comment by CPbN** [comment]
Works like a charm, many thanks !!

**Comment by garnier-quentin** [comment]
You're welcome!

**Pull request closed without merging**
