### PR TITLE
(plugin) apps::protocols::nrpe - enhance perfdata management in NRPE custom mode

### PR DESCRIPTION
**Pull request by OlivierKuziemko**
Updating nrpe protocol to make it works with filter-perfdata while using custom mode nrpe.

### CODE REVIEW

**Comment by garnier-quentin** [comment]
I'm not sure it's very useful. If you use nsclient, you can filter perfdata with nsclient.
And if you use nrpe on linux, you use centreon-plugins obviously so you can filter perfdata ;)

Tell me the case. Maybe we could implement it with an option (not by default).

**Comment by garnier-quentin** [comment]
Ok i see. thanks for the feedback

**Comment by Sims24** [comment]
@OlivierKuziemko 

I will check with Quentin. In the meantime, could you remove the proxmox file that is erroneously included in this PR please?

**Comment by garnier-quentin** [comment]
https://github.com/centreon/centreon-plugins/pull/3703

You have the option ```--parse```

**Pull request closed without merging**
