### PR TITLE
sp_cpu mode for Alteon

### PR DESCRIPTION
**Pull request by skremerkds**
Added ability to measure SP CPU usage (mode=sp_cpu)

The current mode (cpu) only measures MP CPU usage, and does not represent the real CPU usage of the Alteon device.

### CODE REVIEW

**Comment by garnier-quentin** [comment]
Thanks. I prefer to put it with MP CPU usage. Could you give me a snmpwalk of your equipment (following oid: .1.3.6.1.4.1.1872.2.5.1.2.13.1) ?

**Comment by skremerkds** [comment]
Here you go:

SNMPv2-SMI::enterprises.1872.2.5.1.2.13.1.1.1.1 = INTEGER: 1
SNMPv2-SMI::enterprises.1872.2.5.1.2.13.1.1.1.2 = INTEGER: 2
SNMPv2-SMI::enterprises.1872.2.5.1.2.13.1.1.1.3 = INTEGER: 3
SNMPv2-SMI::enterprises.1872.2.5.1.2.13.1.1.1.4 = INTEGER: 4
SNMPv2-SMI::enterprises.1872.2.5.1.2.13.1.1.1.5 = INTEGER: 5
SNMPv2-SMI::enterprises.1872.2.5.1.2.13.1.1.1.6 = INTEGER: 6
SNMPv2-SMI::enterprises.1872.2.5.1.2.13.1.1.2.1 = STRING: "1"
SNMPv2-SMI::enterprises.1872.2.5.1.2.13.1.1.2.2 = STRING: "1"
SNMPv2-SMI::enterprises.1872.2.5.1.2.13.1.1.2.3 = ""
SNMPv2-SMI::enterprises.1872.2.5.1.2.13.1.1.2.4 = ""
SNMPv2-SMI::enterprises.1872.2.5.1.2.13.1.1.2.5 = ""
SNMPv2-SMI::enterprises.1872.2.5.1.2.13.1.1.2.6 = ""
SNMPv2-SMI::enterprises.1872.2.5.1.2.13.1.1.3.1 = INTEGER: 2
SNMPv2-SMI::enterprises.1872.2.5.1.2.13.1.1.3.2 = INTEGER: 2
SNMPv2-SMI::enterprises.1872.2.5.1.2.13.1.1.3.3 = INTEGER: 0
SNMPv2-SMI::enterprises.1872.2.5.1.2.13.1.1.3.4 = INTEGER: 0
SNMPv2-SMI::enterprises.1872.2.5.1.2.13.1.1.3.5 = INTEGER: 0
SNMPv2-SMI::enterprises.1872.2.5.1.2.13.1.1.3.6 = INTEGER: 0
SNMPv2-SMI::enterprises.1872.2.5.1.2.13.1.1.4.1 = INTEGER: 2
SNMPv2-SMI::enterprises.1872.2.5.1.2.13.1.1.4.2 = INTEGER: 2
SNMPv2-SMI::enterprises.1872.2.5.1.2.13.1.1.4.3 = INTEGER: 0
SNMPv2-SMI::enterprises.1872.2.5.1.2.13.1.1.4.4 = INTEGER: 0
SNMPv2-SMI::enterprises.1872.2.5.1.2.13.1.1.4.5 = INTEGER: 0
SNMPv2-SMI::enterprises.1872.2.5.1.2.13.1.1.4.6 = INTEGER: 0
SNMPv2-SMI::enterprises.1872.2.5.1.2.13.1.1.5.1 = INTEGER: 2
SNMPv2-SMI::enterprises.1872.2.5.1.2.13.1.1.5.2 = INTEGER: 2
SNMPv2-SMI::enterprises.1872.2.5.1.2.13.1.1.5.3 = INTEGER: 0
SNMPv2-SMI::enterprises.1872.2.5.1.2.13.1.1.5.4 = INTEGER: 0
SNMPv2-SMI::enterprises.1872.2.5.1.2.13.1.1.5.5 = INTEGER: 0
SNMPv2-SMI::enterprises.1872.2.5.1.2.13.1.1.5.6 = INTEGER: 0

But .1.3.6.1.4.1.1872.2.5.1.2.13.1 is not in the list of recommended OID for monitoring.
See https://support.radware.com/app/answers/answer_view/a_id/16176/~/alteon-recommended-oids-for-snmp-monitoring

**Comment by garnier-quentin** [comment]
Could you test it ?

**Comment by skremerkds** [comment]
Works like a charm!
Thanks.

**Comment by garnier-quentin** [comment]
Thanks for the feedback!

**Pull request closed without merging**
