### PR TITLE
Update 3CX plugin for last v18 updates

### LINKED ISSUE #4083: latest 3cx update 6 18.0 (Build 861) breaks centreon-plugins/apps/voip/3cx/restapi
centreon_3cx_restapi.pl returns: 404 Not Found

### LINKED ISSUE #4608: Is the 3CX Plugin compatible with version 18 U8?
Hi all, 
I tried to configure the plugin to monitor 3CX on a PBX with version 18 Update 8, but the 404 Not Found error is returned.

How can I fix? 

I remain at your disposal for further details/log

Thanks
Ragards

### PR DESCRIPTION
**Pull request by UrBnW**
Hi,

## Description

This patch fixes 3CX plugin, which was broken since v18 update 5.
3CX current version is now v18 update 9.

It then fixes #4083.
It also fixes #4608.

Thx 👍 

## Type of change

- [x] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software

## Target serie

- [ ] 22.04.x
- [ ] 22.10.x
- [ ] 23.04.x
- [x] 23.10.x
- [x] 24.04.x (master)

<h2> How this pull request can be tested ? </h2>

You need a 3CX server to do so.
I tested the plugin against many (more than 10) 3CX servers.

#### Community contributors & Centreon team

- [x] I have followed the **coding style guidelines** provided by Centreon
- [x] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [x] I have commented my code, especially **hard-to-understand areas** of the PR.
- [x] I have **rebased** my development branch on the base branch (master, maintenance).

### CODE REVIEW

**Comment by Bettiol** [comment]
@sdepassio 
Is it possible to accept this PR? I also tested its operation in its environment, and everything works perfectly. Thanks

**Comment by omercier** [comment]
Hi @UrBnW,
With delay, thanks a lot for your contribution :100: 
If I understand correctly, this code change will make the plugin work with 3CX in versions >= 18. But this solution seems to be available on-premise, so I fear this change may break the monitoring of older versions. Am I wrong?
I'm asking this to determine whether this PR must be merged in the current plugin or it must be added as a variant (with a new monitoring connector/pack) to enable the monitoring of both recent and old 3CX systems.
What do you think?

Regards,

**Comment by UrBnW** [comment]
Hi @omercier, thank you for your feedback 👍 
You're right, this plugin gets rid of 3CX v16 support.
But IMO it does not matter, as it is totally outdated, no more supported, since months (years ?) now.
Everybody (should) now run 3CX v18, and 3CX v20 will be released in a couple of days.
Thank you again !

**Comment by UrBnW** [comment]
(@omercier some time has passed since my last commit here, has @garnier-quentin left this repo ? :)

**Comment by omercier** [comment]
This repo, maybe not once and for all, but he has left the company.

**Review by grosbedos — APPROVED** [review]
Tested on my 3cx system (18.0.9.20)
It's working as expected.

**Comment by omercier** [comment]
Hi @UrBnW,
I have created a PR to handle both versions prior and after 3CX 18.0.5 (and probably future versions).
Can you test the code in branch https://github.com/centreon/centreon-plugins/tree/CTOR-360-Community-PR-New-supported-versions-3CX-v18 ?
Thanks a lot for your contribution!

**Comment by omercier** [comment]
@grosbedos can you try it as well and confirm if it fixes your issue?

**Comment by grosbedos** [comment]
Hi, i have tested the branch  https://github.com/centreon/centreon-plugins/tree/CTOR-360-Community-PR-New-supported-versions-3CX-v18 and it's working as expected !

Thanks for your work.

**Comment by omercier** [comment]
Thanks for your feedback @grosbedos :100:

**Comment by UrBnW** [comment]
Hi @omercier,
Sorry for my late reply...
I then just gave #5093 a try, it works perfectly fine 👌
Thank you very much for your rework 👍

**Comment by omercier** [comment]
No problem @UrBnW and thanks for the feedback. 👍🏻 
In order to be able to list the tested versions in our documentation, can you tell me chat version of 3CX you tested the plugin with?

@grosbedos I assume you're still using version `18.0.9.20`

**Comment by UrBnW** [comment]
Tested here with `18.0.9.20`.
To be fair, I'm pretty sure `16.x` is not used anymore :)

**Comment by omercier** [comment]
Yes, probably, but just in case... And we may have to do some other changes with the future versions, so this option will still be useful.

**Comment by UrBnW** [comment]
Sure, the version option will be really useful for future versions (best example is current v20, I'll be back later on regarding this).

**Pull request closed without merging**
