### PR TITLE
Update uptime.pm

### PR DESCRIPTION
**Pull request by benoitb21**

### CODE REVIEW

**Comment by garnier-quentin** [comment]
Thanks for the pull request. I have used a function to display it. Is the result ok ?

**Comment by benoitb21** [comment]
Yes but I thinks that is better if we can choose to limit the "days display" because after it's an average operation. Y (31556926s) => 365.24 days, M (2629743s) => 30.44 days. 
It's not a reality, because each month and year are differents. But, it's my opinion.

**Comment by garnier-quentin** [comment]
I have done the change. Is it better ?

**Comment by benoitb21** [comment]
Perfect :)

**Pull request closed without merging**
