### PR TITLE
(plugin) cloud::azure::management::costs - add list-budget mode

### PR DESCRIPTION
**Pull request by Sims24**
-

### CODE REVIEW

**Comment by matoy** [comment]
i tried but it's KO:
UNKNOWN: Can't call method "value" on unblessed reference at /usr/lib/centreon/plugins/centreon-plugins/cloud/azure/management/costs/mode/listbudgets.pm line 55.

**Comment by Sims24** [comment]
Just pushed something to fix a typo.

**Comment by matoy** [comment]
looks okay now:

List budgets:
[budget = BudgetName][category = Cost][amount = 1000][timegrain = Monthly][id = /subscriptions/xxxxxx-6405-4543-892d-xxxxxxxx/providers/Microsoft.Consumption/budgets/BudgetName]

**Comment by Sims24** [comment]
Great! Thank you

**Review by garnier-quentin — APPROVED** [review]

**Review by lchrdn — APPROVED** [review]

**Pull request merged**
