### PR TITLE
(plugin) snmp_standard::mode::storage adding search of best match mount point

### PR DESCRIPTION
**Pull request by handfreezer**
The main idea is the next one: you want to watch /toto/titi .
Depends of the deployment of your system, you might have mounted /toto or /toto/titi .
By using --path-best-match , the path describe in --storage will select the best match mount point.
So, if you have mount /toto on sda1 and /toto/titi on sda2, the result will detect /toto/titi on sda2 .
BUT, if you only mount /toto on sda1 and there is no mount on /toto/titi, the result will detect /toto on sda1 .

What is the interest:
*you can mount /toto with sda1 with 1GB, now you can check if /toto/serviceA have more than 500MB free, and if /toto/serviceB have more than 2GB free ...
*or you can mount /toto with sda1 with 1GB, and /toto/serviceB on sda2 with 5GB, the check will do the job of taking care of the good mount point.

### CODE REVIEW

**Comment by garnier-quentin** [comment]
I don't really understand your PR. Each mount point has its own space usage. If the mount point Y is mounted in the mount point X, the mount point Y won't take the space usage of the mount X.

**Comment by handfreezer** [comment]
> I don't really understand your PR. Each mount point has its own space usage. If the mount point Y is mounted in the mount point X, the mount point Y won't take the space usage of the mount X.

Hello, The main idea is not to check the mount point but to see a path like a service, without taking care of mount points.
This allow to have different teams for deployment of architecture and for quality.

Exemple : the quality team is waiting for a path like /toto/serviceB with at least 5GB. The Deployment Team can build the path as they want (mounting only /toto, or a specific mount for /toto/serviceB). The test of the Quality Team won't be impacted by the change of Deployment Team and decision how they did it. The fact is that the Quality Team will check the path /toto/serviceB without taking care of the mount point, this option will do the job.

**Review by handfreezer — COMMENTED** [review]
I don't know how to remove my change on README.md file from my pull request?

**Comment by garnier-quentin** [comment]
I still don't understand. You can use regexp to filter and create distinct service:
```
--storage='^/toto$' --name --regexp
```

**Comment by handfreezer** [comment]
Sorry, it won't works.
Say I have this mount:
/toto/service1 : 10GB
/toto : 5GB

Snmp will return 2 mount points : /toto/service1 and /toto
With my new option, I can test available/used space with the param : /toto/service1 and /toto/service2 without taking how mount point are created in fstab.

**Comment by garnier-quentin** [comment]
Could you provide your command line ? Because it should work

**Comment by handfreezer** [comment]
Hello, which command line do you want? The one with my new option or using the regex one? because, with the regex one I failed to get what I want.

**Comment by handfreezer** [comment]
Doing more test, my solution as a bug when no path at all are working. I'm reworking my code... :-(

**Comment by handfreezer** [comment]
After rework, here is the result. 
**First**, I request path status for /mnt/tmp/serviceA and /mnt/tmp/serviceA/serviceB on a signle mounted point /mnt/tmp :

```
root@debian:~/storage_best_mount_point_match# mount |grep mnt/tmp
tmpfs on /mnt/tmp type tmpfs (rw,relatime,size=10240k)

root@debian:~/storage_best_mount_point_match# perl centreon_plugins.pl --plugin=os::linux::snmp::plugin --mode=storage --hostname localhost --statefile-dir /tmp/centreon-plugin/ --storage '/mnt/tmp/serviceA' --path-best-match --name --verbose
OK: Storage '/mnt/tmp' Usage Total: 10.00 MB Used: 0.00 B (0.00%) Free: 10.00 MB (100.00%) | 'count'=1;;;0; 'used'=0B;;;0;10485760
Storage '/mnt/tmp' Usage Total: 10.00 MB Used: 0.00 B (0.00%) Free: 10.00 MB (100.00%)

root@debian:~/storage_best_mount_point_match# perl centreon_plugins.pl --plugin=os::linux::snmp::plugin --mode=storage --hostname localhost --statefile-dir /tmp/centreon-plugin/ --storage '/mnt/tmp/serviceA/serviceB' --path-best-match --name --verbose
OK: Storage '/mnt/tmp' Usage Total: 10.00 MB Used: 0.00 B (0.00%) Free: 10.00 MB (100.00%) | 'count'=1;;;0; 'used'=0B;;;0;10485760
Storage '/mnt/tmp' Usage Total: 10.00 MB Used: 0.00 B (0.00%) Free: 10.00 MB (100.00%)
```

**Second**, I changed the geometry of the deployment of serviceA and serviceB like this:
```
root@debian:~/storage_best_mount_point_match# mount -t tmpfs -o size=15M tmpfs /mnt/tmp/serviceA
root@debian:~/storage_best_mount_point_match# mkdir /mnt/tmp/serviceA/serviceB
root@debian:~/storage_best_mount_point_match# mount -t tmpfs -o size=20M tmpfs /mnt/tmp/serviceA/serviceB
root@debian:~/storage_best_mount_point_match# mount |grep mnt/tmp
tmpfs on /mnt/tmp type tmpfs (rw,relatime,size=10240k)
tmpfs on /mnt/tmp/serviceA type tmpfs (rw,relatime,size=15360k)
tmpfs on /mnt/tmp/serviceA/serviceB type tmpfs (rw,relatime,size=20480k)
```

I cleaned the centreon plugin cache:
`root@debian:~/storage_best_mount_point_match# rm /tmp/centreon-plugin/cache_snmpstandard_localhost_161_storage`

And **Third**, I reused my checks from **First** point:
```
root@debian:~/storage_best_mount_point_match# perl centreon_plugins.pl --plugin=os::linux::snmp::plugin --mode=storage --hostname localhost --statefile-dir /tmp/centreon-plugin/ --storage '/mnt/tmp/serviceA' --path-best-match --name --verbose
OK: Storage '/mnt/tmp/serviceA' Usage Total: 15.00 MB Used: 0.00 B (0.00%) Free: 15.00 MB (100.00%) | 'count'=2;;;0; 'used'=0B;;;0;15728640
Storage '/mnt/tmp/serviceA' Usage Total: 15.00 MB Used: 0.00 B (0.00%) Free: 15.00 MB (100.00%)

root@debian:~/storage_best_mount_point_match# perl centreon_plugins.pl --plugin=os::linux::snmp::plugin --mode=storage --hostname localhost --statefile-dir /tmp/centreon-plugin/ --storage '/mnt/tmp/serviceA/serviceB' --path-best-match --name --verbose
OK: Storage '/mnt/tmp/serviceA/serviceB' Usage Total: 20.00 MB Used: 0.00 B (0.00%) Free: 20.00 MB (100.00%) | 'count'=2;;;0; 'used'=0B;;;0;20971520
Storage '/mnt/tmp/serviceA/serviceB' Usage Total: 20.00 MB Used: 0.00 B (0.00%) Free: 20.00 MB (100.00%)
```

As you can see, in this way, the option will keep the only best mount point that matches the path searched.
If using regex, I didn't find out how to find the best match point if /mn/tmp/ServiceA/serviceB is not a final mount point.

**Comment by garnier-quentin** [comment]
I understand i think. If you set a path (it's not a mountpoint), you want to check the nearest mountpoint ?

**Comment by garnier-quentin** [comment]
It's ok for me.

**Comment by handfreezer** [comment]
> I understand i think. If you set a path (it's not a mountpoint), you want to check the nearest mountpoint ?

Exactly ( i feel stupid not to be able to explain it so simply)

**Comment by handfreezer** [comment]
Now i need some help because i don't know how to remove the readme file from my pull request...

**Comment by garnier-quentin** [comment]
I will do the PR next week. don't worry

**Comment by garnier-quentin** [comment]
https://github.com/centreon/centreon-plugins/pull/3695

**Pull request closed without merging**
