### PR TITLE
(plugin) apps::protocols::sftp - add sftp monitoring

### PR DESCRIPTION
**Pull request by OlivierKuziemko**
Add plugin to check SFTP servers using NET::SFTP::Foreign module
Based on FTP plugin
Available modes: 
Login
Date
Filecount

### CODE REVIEW

**Comment by garnier-quentin** [comment]
Thanks. It's a nice but could you use my ssh/sftp module: https://github.com/garnier-quentin/perl-libssh
If some capabilities are missing (sftp class), please tell and i will add it.

**Comment by OlivierKuziemko** [comment]
I'll give a try

**Comment by garnier-quentin** [comment]
I have take a look. You execute the ls command. But it's not a sftp capabilities. You are doing ssh execution command.

**Comment by garnier-quentin** [comment]
I have made a mistake. it's sftp commands. With the following library: https://github.com/garnier-quentin/perl-libssh/blob/master/lib/Libssh/Sftp.pm, you can do the same:
* readdir (ls)
* stat_file (stat)

**Comment by OlivierKuziemko** [comment]
I'm working on it but I don't have much time currently.
I will release a new version with your lib asap

**Comment by garnier-quentin** [comment]
I have done it: https://github.com/centreon/centreon-plugins/pull/3634
You'll need libssh 0.9 for some modes.

**Pull request closed without merging**
