### PR TITLE
Add option for idrac6 support

### PR DESCRIPTION
**Pull request by Gilum**
globalSystemStatus (oid 1.3.6.1.4.1.674.10892.5.2.1) does not exist on idrac6
Add drsGlobalSystemStatus (oid 1.3.6.1.4.1.674.10892.2.2.1) and option --idrac6

### CODE REVIEW

**Comment by garnier-quentin** [comment]
Do you have the mib file ? I think we can do it better. Do a leef on the 2 oids. And check idrac6 and after idrac < 6.

**Comment by Gilum** [comment]
http://dezoils.com/wp-content/uploads/2014/11/iDRAC-MIB.zip
idrac => 7 : IDRAC-MIB
idrac 6 : DELL-RAC-MIB

[root@### ~]# snmpwalk -v2c -c public <idrac6_server> 1.3.6.1.4.1.674.10892.5
SNMPv2-SMI::enterprises.674.10892.5 = No Such Object available on this agent at this OID

[root@### ~]# snmpwalk -v2c -c public <idrac6_server> 1.3.6.1.4.1.674.10892
SNMPv2-SMI::enterprises.674.10892.2.1.1.1.0 = STRING: "Integrated Dell Remote Access Controller 6"
SNMPv2-SMI::enterprises.674.10892.2.1.1.2.0 = STRING: "iDRAC6"
SNMPv2-SMI::enterprises.674.10892.2.1.1.3.0 = STRING: "This system component provides a complete set of remote management functions for Dell PowerEdge servers"
SNMPv2-SMI::enterprises.674.10892.2.1.1.4.0 = STRING: "Dell"
SNMPv2-SMI::enterprises.674.10892.2.1.1.5.0 = STRING: "1.98 (Build \"08\")"
SNMPv2-SMI::enterprises.674.10892.2.1.1.6.0 = ""
SNMPv2-SMI::enterprises.674.10892.2.1.1.7.0 = STRING: "https://<idrac6_server>:443"
SNMPv2-SMI::enterprises.674.10892.2.1.1.8.0 = ""
SNMPv2-SMI::enterprises.674.10892.2.1.1.11.0 = STRING: "######"
SNMPv2-SMI::enterprises.674.10892.2.1.1.14.0 = INTEGER: 10
SNMPv2-SMI::enterprises.674.10892.2.1.2.1.0 = STRING: "1.98"
SNMPv2-SMI::enterprises.674.10892.2.2.1.0 = INTEGER: 3

**Comment by garnier-quentin** [comment]
Thanks. I'll fix it tonight.

**Comment by garnier-quentin** [comment]
aeb31bbc3355ad0e0a667500acb2e5370537e96e

Thanks. I have done the change. You could test.

**Pull request closed without merging**
