### PR TITLE
(plugin) cloud::azure::management::costs - new modes to check azure config compliance

### PR DESCRIPTION
**Pull request by Sims24**
Closes https://github.com/centreon/centreon-plugins/pull/3892

Credit goes to @matoy , thank you!

### CODE REVIEW

**Comment by Sims24** [comment]
@matoy, new modes and options

Orphan resources:

```
perl centreon_plugins.pl --plugin=cloud::azure::management::costs::plugin --custommode='api' --mode='orphan-resources' --subscription='xxx' --tenant='xxx' --client-id='xxx' --client-secret='xxx' --verbose
OK: Orphaned resources: 44 | 'azure.resources.orphaned.count'=44;;;0;180 'azure.manageddisks.orphaned.count'=5;;;0;64 'azure.nics.orphaned.count'=12;;;0;77 'azure.nsgs.orphaned.count'=8;;;0;20 'azure.publicips.orphaned.count'=0;;;0;0 'azure.routetables.orphaned.count'=12;;;0;12 'azure.snapshots.orphaned.count'=7;;;0;7
Managed Disks orphaned list:[xxx, xxx, xxx, xxx, xxx]
NICs orphaned list:[xxx, xxx, xxx, xxx, xxx, xxx, xxx, xxx, xxx]
NSGs orphaned list:[xxx, xxx, xxx, xxx, xxx, xxx, xxx, xxx]
Public IPs orphaned list:[xxx, xxx, xxx]
Route tables orphaned list:[xxx, xxx, xxx, xxx, xxx, xxx, xxx, xxx, xxx, xxx, xxx, xxx]
Snapshots orphaned list:[xxx, xxx, xxx, xxx, xxx, xxx, xxx]
```

Tag compliance:

```
perl centreon_plugins.pl --plugin=cloud::azure::management::costs::plugin --custommode='api' --mode='tags-compliance' --subscription='xxx' --tenant='xxx' --client-id='xxx' --client-secret='xxx' --verbose
OK: Uncompliant resources: 53 | 'uncompliant-resource'=53;;;0;54 'uncompliant-vms'=53;;;0;54
Virtual Machines with uncompliant tags:[<xxx * 53>]
``` 

Hybrid benefits 

```
perl centreon_plugins.pl --plugin=cloud::azure::management::costs::plugin --custommode='api' --mode='hybrid-benefits' --subscription='xxx' --tenant='xxx' --client-id='xxx' --client-secret='xxx' --verbose
OK: Resources without hybrid benefits: 3 | 'azure.resources.nohybridbenefits.count'=3;;;0;58 'azure.vm.nohybridbenefits.count'=0;;;0;0 'azure.sqlvm.nohybridbenefits.count'=1;;;0;2 'azure.sqldatabase.nohybridbenefits.count'=0;;;0;0 'azure.elasticpool.nohybridbenefits.count'=2;;;0;2
SQL Virtual Machines withtout hybrid benefits:[xxx]
SQL Elastic pools withtout hybrid benefits:[xxx, xxx]
```

**Comment by matoy** [comment]
Hi @Sims24.
Thank you for all this.
I did some field checks...

Hybrid Benefits mode est OK

For orphan mode, there are some typos:
should be publicips on these 2:
image

should be route_tables here:
image

except that, orphan mode est OK.

For tags mode:
i think there is something missing here; if test with just a tag name (without checking its value), it's always uncompliant.
image

**Comment by Sims24** [comment]
@matoy could you please check again the tags-compliance mode? 

This is kind of brainfuck and I'm not sure I actually fixed anything.

**Comment by matoy** [comment]
hi.
Tag without value is okay, tag with value is working as well
Several tag parameters with same name and different values is not working but i guess it should not be supported, there would be only one tag paramater per tag name with proper regexp matching several values (see below)

so for me, everything is okay, great new checks!!!

just to share my use case, i use this check if VMs have a start/stop tag indicating wether they should be started/stopped on some internally defined schedules, on 24/7 or only on demand (we have an automation thats browses VM and issues start/stop actions based on that tag).

--tags='finopsstartstop => On-Demand|6am-9pm-.*|24x7-Fulltime'

**Review by lchrdn — DISMISSED** [review]

**Comment by Sims24** [comment]
Thanks! Yes I love these new capabilities we bring to Azure, and this is mainly thanks to your contributions so kudos! @lchrdn also brought something that you might like if you do not always define budget. It's about querying the cost of a subscription, resource-group or based on tags. Give it a try ;)

I handled explicitely the thing you mentionned in your last message. Using this: `--tags='Environment => Dev' --tags='Environment => Prod'` will result in the following error message: 

`UNKNOWN: Using multiple --tags option with the same key is forbiden. Please use regexp on the value instead`

Also updated the help according to the option capability: 

```
=item B<--tags>

Can be multiple. Allow you to specify tags that should be present. All tags must match a resource's configuration
to make it a compliant one.

What you cannot do: 

- specifying the same key in different options: --tags='Environment => Prod' --tags='Environment => Dev'

What you can do: 
- check for multiple value for a single key: --tags='Environment => Dev|Prod'
- check for a key, without minding about its value: --tags='Version'
- combine the two: --tags='Environment => Dev|Prod' --tags='Version'
```

**Review by lchrdn — APPROVED** [review]

**Pull request merged**
