### PR TITLE
Add 18 modes for Kingdee EAS, 2 for mysql.

### PR DESCRIPTION
**Pull request by aladdinchan**
EAS is a popular ERP system in Chinese enterprise market,  created by Kingdee.  [http://www.kingdee.com.hk/en/products/eas](http://www.kingdee.com.hk/en/products/eas)

mysql mode tablescount and openfiles is forked by databasesizes and opentables mode.

Some examples:
perl centreon-plugins.pl --plugin=apps::kingdee::eas::plugin --mode=datasource --datasource=E850NEWDB --hostname=easdemo.kingdee.com --port=7500
OK: InitialPoolSize: 0 - MaxPoolSize: 80 - IdleTimeout: 1200 - ActiveConnectionCount: 0 - CurrentConnectionCount: 10 - MaxConnectionCount: 17 - CreateCount: 22 - CloseCount: -1

perl centreon-plugins/centreon_plugins.pl --plugin=apps::kingdee::eas::plugin --mode=memory --hostname=easdemo.kingdee.com --port 7500
OK: Heap Memory: init 6291456000 , max 8388608000 ,used 4136779688 ,commited 6327868416 - NonHeap Memory: init 0 , max -1 ,used 354302652 ,commited 420828420

image

image

image

image

### CODE REVIEW

**Comment by garnier-quentin** [comment]
Thank you your PR. Could you use the custom to manage http options ? (it'll save many code lines).
You can look that plugin code: apps/elasticsearch/restapi

**Comment by garnier-quentin** [comment]
Moreover the ERP seems to be an Oracle database and java server. You cannot use directly oracle plugin and jolokia on the jvm ? If not, we'll use that api.

**Comment by aladdinchan** [comment]
I wrote these mode based on nginx mode one year ago， It use simple api. I did not knew custom api. :-( .  Custom api is very good , but I need some time to learn it. May I refactoring code in next version？

EAS system usually deployed inside firewall ， in many cases, centreon machine only has permission to access app server. So we designed a unified layer to collect metrics in app through JSPs. Centreon plugins <- JSPs (implemented use JMX/SQL//JavaClass/ShellScript etc. return kv metrics) <- App/DB/Other Machine in firewall. It's a solution for this scenario and easy to manage and maintain for us. 

About oracle database plugins. Except reason above, there have no mode like our oraclesession/oracletables/... , maybe I can write some mode directly for oracle in future.

Jolokia is a perfect restapi bridge for jmx. We will try it , estimate security risk, it may appear in next EAS version. 

Thank you a lot.

**Comment by aladdinchan** [comment]
I wrote these modes based on nginx mode one year ago， It use simple api. I did not knew custom api. :-( .  Custom api is very good , but I need some time to learn it. May I refactoring code in next version？

EAS system usually deployed inside firewall,  in many cases, centreon machine only has permission to access app server. So we designed a unified layer to collect metrics in app through JSPs. Centreon plugins <- JSPs (implemented use JMX/SQL//JavaClass/ShellScript etc. return kv metrics) <- App/DB/Other in firewall. It's a solution for this scenario and easy to manage and maintain for us. 

About oracle database plugins. Except reason above, there have no mode like our oraclesession/oracletables/... , maybe I can write some mode directly for oracle in future.

Jolokia is a perfect restapi bridge for jmx. We will try it , estimate security risk, it may appear in next EAS version. 

Thank you a lot.

**Comment by garnier-quentin** [comment]
If your unified layer is accessible for everyone ? Otherwise it's too specific.

**Comment by aladdinchan** [comment]
This layer is specific for EAS. It is not a general purpose framework or agent, so it only work for our EAS,  cannot work for other system like SAP & oracle ERP.  It is why I put these modes in app::kingdee::eas.  

BTW,  two mysql modes is general for anyone.

**Comment by garnier-quentin** [comment]
If it's for your only EAS i cannot accept the pull request. centreon-plugins is for everyone. 
For the MySQL you can create another pull request.

**Comment by aladdinchan** [comment]
Maybe I did not explained clear.  It's only for EAS means like vmware mode only for vmware , peoplesoft mode only for peoplesoft and so on.  Anyone can use EAS modes If they are EAS customers.  EAS have millions users in china,  they complete thousands of transactions every second in EAS.

**Comment by garnier-quentin** [comment]
So the unified layer is for all clients ?

**Comment by aladdinchan** [comment]
Yes. It is a building block inside EAS product for all clients.

**Comment by garnier-quentin** [comment]
Great. So i will do some refactoring for it ;)

**Comment by aladdinchan** [comment]
Great!  It‘s my honor, Thank you very much.

**Comment by garnier-quentin** [comment]
I have done some cleaning code. Maybe i'll do it again. Could you try it with new version ?

**Comment by aladdinchan** [comment]
All modes is working，Except oraclesession mode , Wrong variable name "$cpu   wait", should be $cpuandwait， Ref: https://github.com/aladdinchan/centreon-plugins/commit/0a55304cdb804c3e73fcae182c1a52ceb3f0dc49

**Pull request merged**
