### PR TITLE
Standard CPU, add the max used core in perfdata

### PR DESCRIPTION
**Pull request by CPbN**
Hi,

This PR adds the max used CPU core stats in standard CPU mode perfdata output.

Thank you :+1:

### CODE REVIEW

**Comment by garnier-quentin** [comment]
Sorry, but i should be done on your monitoring system (to get a curve with max values).

**Comment by CPbN** [comment]
Grafana easily does this, but I'm not sure about Centreon itself, so this was the easiest way.
I'll then dig into Centreon graph possibilities.

**Comment by garnier-quentin** [comment]
If centreon cannot, you can ask for it in centreon github.

**Comment by CPbN** [comment]
Still @garnier-quentin, there is one major advantage computing max value at plugin level.
Think about a CPU with 24 cores.
You don't care about the 24 individual core usage values, but you only need the max value.
With max value computed at plugin level (and with `--filter-perfdata` to remove individual core values), you only store one data series (in SQL and RRD) instead of 24.
Which is a nice performance and storage improvement.

**Comment by garnier-quentin** [comment]
It depends what you want. With change-perfdata and extend-perfdata option, it cannot work. It will need another option.

**Comment by CPbN** [comment]
I meant that with this PR we would get :
`'total_cpu_avg'=5.00%;;;; 'cpu_0'=9.00%;;;; ... 'cpu_23'=1.00%;;;; 'cpu_max'=9.00%;;;;`

So, using `--filter-data='total_cpu_avg|cpu_max'` we would easily get :
`'total_cpu_avg'=5.00%;;;; 'cpu_max'=9.00%;;;;`

Of course this PR is related to this CPU mode only, and as first thought in #1427, perhaps a more general option could make sense, if ever you think this makes sense :)

**Comment by CPbN** [comment]
Thanks to #1442 :
` --filter-perfdata='^total_cpu_avg$|^core_cpu_max$'`
`--extend-perfdata-group=',core_cpu_max,max(cpu_[0-9+]),%'`
👍

**Pull request closed without merging**
