### PR TITLE
Add possiblity to use str2time()

### PR DESCRIPTION
**Pull request by CPbN**
Hi,

This PR allows to use `str2time()` in _--convert-custom-values_ option of _string-value_ mode, in _apps::protocols::snmp_ plugin.

For example :
`--convert-custom-values='(time - str2time($value)) / 3600'`

Many thanks 👍

### CODE REVIEW

**Comment by garnier-quentin** [comment]
I don't want to force at using a specific module. Please add an option to load your module

**Comment by CPbN** [comment]
Thank you @garnier-quentin for your feedback.
Should it be an option specific to this plugin only, or a more global option which would be inherited by all plugins ?

**Comment by garnier-quentin** [comment]
it should be specific

**Comment by CPbN** [comment]
Should be OK with last commit :wink:
We can now do :
`--use-perl-mod='Date::Parse' --convert-custom-values='Date::Parse::str2time($value)'`
And many other things as the option is rather generic.
Thx 👍

**Comment by CPbN** [comment]
Many thx Quentin !

**Pull request merged**
