### PR TITLE
Add missing option to set SSL options

### PR DESCRIPTION
**Pull request by alfredosilvestre-natixis**
When using this plugin I noticed that since our prime had a self-signed certificate, the plugin was not taking this into account and this fixes the issue.

### CODE REVIEW

**Comment by garnier-quentin** [comment]
You can already used that option:
```
Backend lwp Options:
    --ssl-opt
            Set SSL Options (--ssl-opt="SSL_version => TLSv1"
            --ssl-opt="SSL_verify_mode => SSL_VERIFY_NONE").

    --ssl   Set SSL version (--ssl=TLSv1).

Backend Curl Options:
    --curl-opt
            Set CURL Options (--curl-opt="CURLOPT_SSL_VERIFYPEER => 0"
            --curl-opt="CURLOPT_SSLVERSION => CURL_SSLVERSION_TLSv1_1" ).
```

**Comment by alfredosilvestre-natixis** [comment]
Yes, but it is not working with this specific plugin "network::cisco::prime::restapi::custom::api"

Output is -> Unknown option: ssl-opt

**Comment by garnier-quentin** [comment]
For me, it's working:
```
perl centreon_plugins.pl --plugin=network/cisco/prime/restapi/plugin.pm --mode=ap-usage --ssl-opt="tt" --hostname="test" 
```

Which version do you use ? If you use --http-backend=curl, it's --curl-opt

**Comment by alfredosilvestre-natixis** [comment]
We had an old version of the http plugin, after updating everything works.

Thanks

**Pull request closed without merging**
