### PR TITLE
(plugin) storage::emc::xtremio::restapi - Add new modes [dataprotectiongroups, storagecontrollers]

### PR DESCRIPTION
**Pull request by bert-jan**
Additional checks for XtremIO SC and DPG.

### CODE REVIEW

**Comment by garnier-quentin** [comment]
Could you provide the curl command and results for the new modes ?

**Comment by bert-jan** [comment]
Hi,

I've tested with the following commands:

curl -k https://xms.domain.local/api/json/v2/types/data-protection-groups
-u user:pass

{
    "data-protection-groups": [
        {
            "href": "
https://xms.domain.local/api/json/v2/types/data-protection-groups/1",
            "name": "X1-DPG-1",
            "sys-name": "xtremio01"
        },
        {
            "href": "
https://xms.domain.local/api/json/v2/types/data-protection-groups/2",
            "name": "X1-DPG-2",
            "sys-name": "xtremio01"
        }
    ],
    "links": [
        {
            "href": "
https://xms.domain.local/api/json/v2/types/data-protection-groups/",
            "rel": "self"
        }
    ]
}

curl -k https://xms.domain.local/api/json/v2/types/data-protection-groups/1
-u user:pass
curl -k https://xms.domain.local/api/json/v2/types/data-protection-groups/2
-u user:pass

{
    "content": {
        "dpg-state": "normal",
        "iops": "62086",
        "available-rebuilds": "22",
        "ssd-preparation-progress": 0,
        "index": 1,
        "num-of-nodes": 2,
        "rg-ud-ssd-percent-free-space": 0,
        "ssd-space-in-use": "0",
        "integrating-slot-num": 255,
        "brick-name": "X1",
        "protection-state": "normal"
        "rebuild-in-progress": "done",
        "rebalance-progress": "null",
-- output cut --


Plugin outputs:
OK: All DPG are OK |

curl -k https://xms.domain.local/api/json/v2/types/storage-controllers -u
user:pass

{
    "storage-controllers": [
        {
            "href": "
https://xms.domain.local/api/json/v2/types/storage-controllers/1",
            "name": "X1-SC1",
            "sys-name": "xtremio01"
        },
        {
            "href": "
https://xms.domain.local/api/json/v2/types/storage-controllers/2",
            "name": "X1-SC2",
            "sys-name": "xtremio01"
        }
    ],
    "links": [
        {
            "href": "
https://xms.domain.local/api/json/v2/types/storage-controllers/",
            "rel": "self"
        }
    ]
}

curl -k https://xms.domain.local/api/json/v2/types/storage-controllers/1 -u
user:pass
curl -k https://xms.domain.local/api/json/v2/types/storage-controllers/2 -u
user:pass

{
    "content": {
        "ib2-link-error-recoveries": 0,
        "fru-lifecycle-state": "healthy",
        "obj-severity": "information",
        "dimm-health-state": "level_1_clear",
        "ib2-last-24h-number-of-port-problems": 0,
        "local-disk-controller-fw-version": "",
        "num-of-monitored-upses": 0,
        "rg-id": [
            "<RG-ID>",
            "X1-DPG-1",
            1
        ],
        "dimm-corr-errors-th2": 2500,
        "jbod-dn": "false",
        "ib1-port-in-peer-index": 1,
        "bios-fw-version": "<FW-VERSION>",
        "ib2-link-rate-in-gbps": "fdr",
        "ib2-symbol-errors": 0,
        "ib1-port-health-state": "healthy",
        "ib1-link-downed": 0,
        "sas1-port-rate": "12gbps",
        "fc-hba-model": "Emulex",
        "ib2-port-state": "up",
        "brick-name": "X1",
        "node-csid": 8,
        "os-upgrade-current-step-info": null,
        "ib1-last-24h-number-of-port-faults": 0,
        "sas1-port-health-state": "healthy",
        "sas1-port-state": "up",
        "node-fp-temperature-state": "normal",
        "tag-list": [],
        "pci-disk-controller-hw-revision": null,
        "ib-addr1": "169.254.0.1",
        "ib2-port-rcv-errors": 0,
        "node-sw-build": "10",
        "acc-dimm-correctable-errors": 1,
        "ib2-port-in-peer-index": 2,
        "node-health-state": "healthy",
        "node-mgr-conn-state": "connected",
        -- output cut --


Plugin outputs:
OK: All Storage Controllers are OK |


Best regards,
Bert-Jan

Op do 30 dec. 2021 om 15:59 schreef qgarnier ***@***.***>:

**Comment by garnier-quentin** [comment]
I don't understand. In the mode 'dataprotectiongroups': you call that api endpoint:
```
my @items = $xtremio->get_items(url => $urlbase,
                                    obj => 'storage-controllers');
```

Is it ok ?

**Comment by bert-jan** [comment]
Well spotted. Fixed it by another commit.

Op wo 2 feb. 2022 om 11:05 schreef qgarnier ***@***.***>:

**Pull request closed without merging**
